/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AbstractBackgroundJobStatusInfo model module.
 * @module model/AbstractBackgroundJobStatusInfo
 * @version 3.0
 */
export default class AbstractBackgroundJobStatusInfo {
  /**
   * Constructs a new <code>AbstractBackgroundJobStatusInfo</code>.
   * Status information of a background job
   * @alias module:model/AbstractBackgroundJobStatusInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AbstractBackgroundJobStatusInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AbstractBackgroundJobStatusInfo} obj Optional instance to populate.
   * @return {module:model/AbstractBackgroundJobStatusInfo} The populated <code>AbstractBackgroundJobStatusInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AbstractBackgroundJobStatusInfo();
      if (data.hasOwnProperty('progressPercentage'))
        obj.progressPercentage = ApiClient.convertToType(data['progressPercentage'], 'Number');
      if (data.hasOwnProperty('stepInProgress'))
        obj.stepInProgress = ApiClient.convertToType(data['stepInProgress'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * Progress in percentage (calculated based on pre-set weights)
 * @member {Number} progressPercentage
 */
AbstractBackgroundJobStatusInfo.prototype.progressPercentage = undefined;

/**
 * Step currently in progress
 * @member {String} stepInProgress
 */
AbstractBackgroundJobStatusInfo.prototype.stepInProgress = undefined;

/**
 * Type of status info object
 * @member {String} type
 */
AbstractBackgroundJobStatusInfo.prototype.type = undefined;

