/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AutomatedTestCaseRunResult from './AutomatedTestCaseRunResult';
import TrackerItem from './TrackerItem';

/**
 * The AutomatedTestRunRequest model module.
 * @module model/AutomatedTestRunRequest
 * @version 3.0
 */
export default class AutomatedTestRunRequest {
  /**
   * Constructs a new <code>AutomatedTestRunRequest</code>.
   * Request model to create a test run from test case runs
   * @alias module:model/AutomatedTestRunRequest
   * @class
   * @param testCaseTrackerId {Number} ID of the Test Case tracker
   * @param testResults {Array.<module:model/AutomatedTestCaseRunResult>} Test case results to include into the test run
   */
  constructor(testCaseTrackerId, testResults) {
    this.testCaseTrackerId = testCaseTrackerId;
    this.testResults = testResults;
  }

  /**
   * Constructs a <code>AutomatedTestRunRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomatedTestRunRequest} obj Optional instance to populate.
   * @return {module:model/AutomatedTestRunRequest} The populated <code>AutomatedTestRunRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AutomatedTestRunRequest();
      if (data.hasOwnProperty('createNonExistentTestCases'))
        obj.createNonExistentTestCases = ApiClient.convertToType(data['createNonExistentTestCases'], 'Boolean');
      if (data.hasOwnProperty('testCaseTrackerId'))
        obj.testCaseTrackerId = ApiClient.convertToType(data['testCaseTrackerId'], 'Number');
      if (data.hasOwnProperty('testResults'))
        obj.testResults = ApiClient.convertToType(data['testResults'], [AutomatedTestCaseRunResult]);
      if (data.hasOwnProperty('testRunModel'))
        obj.testRunModel = TrackerItem.constructFromObject(data['testRunModel']);
    }
    return obj;
  }
}

/**
 * Flag to create new test cases from testResults if necessary
 * @member {Boolean} createNonExistentTestCases
 */
AutomatedTestRunRequest.prototype.createNonExistentTestCases = undefined;

/**
 * ID of the Test Case tracker
 * @member {Number} testCaseTrackerId
 */
AutomatedTestRunRequest.prototype.testCaseTrackerId = undefined;

/**
 * Test case results to include into the test run
 * @member {Array.<module:model/AutomatedTestCaseRunResult>} testResults
 */
AutomatedTestRunRequest.prototype.testResults = undefined;

/**
 * @member {module:model/TrackerItem} testRunModel
 */
AutomatedTestRunRequest.prototype.testRunModel = undefined;

