/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AutomatedTestCaseRunResult model module.
 * @module model/AutomatedTestCaseRunResult
 * @version 3.0
 */
export default class AutomatedTestCaseRunResult {
  /**
   * Constructs a new <code>AutomatedTestCaseRunResult</code>.
   * Request model to create a test run from test case
   * @alias module:model/AutomatedTestCaseRunResult
   * @class
   * @param name {String} Name of the Test Case
   * @param result {module:model/AutomatedTestCaseRunResult.ResultEnum} Result of the test case
   */
  constructor(name, result) {
    this.name = name;
    this.result = result;
  }

  /**
   * Constructs a <code>AutomatedTestCaseRunResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomatedTestCaseRunResult} obj Optional instance to populate.
   * @return {module:model/AutomatedTestCaseRunResult} The populated <code>AutomatedTestCaseRunResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AutomatedTestCaseRunResult();
      if (data.hasOwnProperty('conclusion'))
        obj.conclusion = ApiClient.convertToType(data['conclusion'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('groupName'))
        obj.groupName = ApiClient.convertToType(data['groupName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('result'))
        obj.result = ApiClient.convertToType(data['result'], 'String');
      if (data.hasOwnProperty('runTime'))
        obj.runTime = ApiClient.convertToType(data['runTime'], 'Number');
    }
    return obj;
  }
}

/**
 * Optional Test Case Run conclusion
 * @member {String} conclusion
 */
AutomatedTestCaseRunResult.prototype.conclusion = undefined;

/**
 * Description of the Test Case
 * @member {String} description
 */
AutomatedTestCaseRunResult.prototype.description = undefined;

/**
 * Group name of the Test Case
 * @member {String} groupName
 */
AutomatedTestCaseRunResult.prototype.groupName = undefined;

/**
 * Name of the Test Case
 * @member {String} name
 */
AutomatedTestCaseRunResult.prototype.name = undefined;

/**
 * Allowed values for the <code>result</code> property.
 * @enum {String}
 * @readonly
 */
AutomatedTestCaseRunResult.ResultEnum = {
  /**
   * value: "PASSED"
   * @const
   */
  PASSED: "PASSED",

  /**
   * value: "FAILED"
   * @const
   */
  FAILED: "FAILED",

  /**
   * value: "BLOCKED"
   * @const
   */
  BLOCKED: "BLOCKED",

  /**
   * value: "NOT_APPLICABLE"
   * @const
   */
  NOT_APPLICABLE: "NOT_APPLICABLE"
};
/**
 * Result of the test case
 * @member {module:model/AutomatedTestCaseRunResult.ResultEnum} result
 */
AutomatedTestCaseRunResult.prototype.result = undefined;

/**
 * Optional runtime in seconds
 * @member {Number} runTime
 */
AutomatedTestCaseRunResult.prototype.runTime = undefined;

