/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BaseTrackerFieldChoiceOption model module.
 * @module model/BaseTrackerFieldChoiceOption
 * @version 3.0
 */
export default class BaseTrackerFieldChoiceOption {
  /**
   * Constructs a new <code>BaseTrackerFieldChoiceOption</code>.
   * Describes a Choice Option field configuration.
   * @alias module:model/BaseTrackerFieldChoiceOption
   * @class
   * @param type {String} 
   */
  constructor(type) {
    this.type = type;
  }

  /**
   * Constructs a <code>BaseTrackerFieldChoiceOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseTrackerFieldChoiceOption} obj Optional instance to populate.
   * @return {module:model/BaseTrackerFieldChoiceOption} The populated <code>BaseTrackerFieldChoiceOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BaseTrackerFieldChoiceOption();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
BaseTrackerFieldChoiceOption.prototype.type = undefined;

