/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BatchGetTrackerItemReviewsRequest model module.
 * @module model/BatchGetTrackerItemReviewsRequest
 * @version 3.0
 */
export default class BatchGetTrackerItemReviewsRequest {
  /**
   * Constructs a new <code>BatchGetTrackerItemReviewsRequest</code>.
   * Request model to fetch Tracker Item Reviews for multiple Tracker Items.
   * @alias module:model/BatchGetTrackerItemReviewsRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BatchGetTrackerItemReviewsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BatchGetTrackerItemReviewsRequest} obj Optional instance to populate.
   * @return {module:model/BatchGetTrackerItemReviewsRequest} The populated <code>BatchGetTrackerItemReviewsRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BatchGetTrackerItemReviewsRequest();
      if (data.hasOwnProperty('baselineId'))
        obj.baselineId = ApiClient.convertToType(data['baselineId'], 'Number');
      if (data.hasOwnProperty('itemIds'))
        obj.itemIds = ApiClient.convertToType(data['itemIds'], ['Number']);
    }
    return obj;
  }
}

/**
 * Optional Baseline ID
 * @member {Number} baselineId
 */
BatchGetTrackerItemReviewsRequest.prototype.baselineId = undefined;

/**
 * List of Tracker Item IDs
 * @member {Array.<Number>} itemIds
 */
BatchGetTrackerItemReviewsRequest.prototype.itemIds = undefined;

