/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractFieldValue from './AbstractFieldValue';

/**
 * The BoolFieldValue model module.
 * @module model/BoolFieldValue
 * @version 3.0
 */
export default class BoolFieldValue extends AbstractFieldValue {
  /**
   * Constructs a new <code>BoolFieldValue</code>.
   * Value container of a bool field
   * @alias module:model/BoolFieldValue
   * @class
   * @extends module:model/AbstractFieldValue
   * @param type {} Type of the field
   */
  constructor(type) {
    super(type);
  }

  /**
   * Constructs a <code>BoolFieldValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoolFieldValue} obj Optional instance to populate.
   * @return {module:model/BoolFieldValue} The populated <code>BoolFieldValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BoolFieldValue();
      AbstractFieldValue.constructFromObject(data, obj);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Value of the field
 * @member {Boolean} value
 */
BoolFieldValue.prototype.value = undefined;

