/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import BaseTrackerFieldChoiceOption from './BaseTrackerFieldChoiceOption';
import ReferenceFilterBasedChoiceReferenceFilter from './ReferenceFilterBasedChoiceReferenceFilter';

/**
 * The ChoiceDocuments model module.
 * @module model/ChoiceDocuments
 * @version 3.0
 */
export default class ChoiceDocuments extends BaseTrackerFieldChoiceOption {
  /**
   * Constructs a new <code>ChoiceDocuments</code>.
   * Describes a Documents Choice Option field configuration.
   * @alias module:model/ChoiceDocuments
   * @class
   * @extends module:model/BaseTrackerFieldChoiceOption
   * @param type {} 
   */
  constructor(type) {
    super(type);
  }

  /**
   * Constructs a <code>ChoiceDocuments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChoiceDocuments} obj Optional instance to populate.
   * @return {module:model/ChoiceDocuments} The populated <code>ChoiceDocuments</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChoiceDocuments();
      BaseTrackerFieldChoiceOption.constructFromObject(data, obj);
      if (data.hasOwnProperty('referenceFilters'))
        obj.referenceFilters = ApiClient.convertToType(data['referenceFilters'], [ReferenceFilterBasedChoiceReferenceFilter]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ReferenceFilterBasedChoiceReferenceFilter>} referenceFilters
 */
ChoiceDocuments.prototype.referenceFilters = undefined;

