/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractReference from './AbstractReference';

/**
 * The DependencyEntityReference model module.
 * @module model/DependencyEntityReference
 * @version 3.0
 */
export default class DependencyEntityReference extends AbstractReference {
  /**
   * Constructs a new <code>DependencyEntityReference</code>.
   * Reference to an entity in dependency path
   * @alias module:model/DependencyEntityReference
   * @class
   * @extends module:model/AbstractReference
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DependencyEntityReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DependencyEntityReference} obj Optional instance to populate.
   * @return {module:model/DependencyEntityReference} The populated <code>DependencyEntityReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DependencyEntityReference();
      AbstractReference.constructFromObject(data, obj);
      if (data.hasOwnProperty('typeId'))
        obj.typeId = ApiClient.convertToType(data['typeId'], 'Number');
    }
    return obj;
  }
}

/**
 * Type ID of entity
 * @member {Number} typeId
 */
DependencyEntityReference.prototype.typeId = undefined;

