/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MaintenanceModeProperties from './MaintenanceModeProperties';

/**
 * The MaintenanceMode model module.
 * @module model/MaintenanceMode
 * @version 3.0
 */
export default class MaintenanceMode {
  /**
   * Constructs a new <code>MaintenanceMode</code>.
   * Basic properties of maintenance mode
   * @alias module:model/MaintenanceMode
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MaintenanceMode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MaintenanceMode} obj Optional instance to populate.
   * @return {module:model/MaintenanceMode} The populated <code>MaintenanceMode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MaintenanceMode();
      if (data.hasOwnProperty('properties'))
        obj.properties = MaintenanceModeProperties.constructFromObject(data['properties']);
      if (data.hasOwnProperty('systemMode'))
        obj.systemMode = ApiClient.convertToType(data['systemMode'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/MaintenanceModeProperties} properties
 */
MaintenanceMode.prototype.properties = undefined;

/**
 * Allowed values for the <code>systemMode</code> property.
 * @enum {String}
 * @readonly
 */
MaintenanceMode.SystemModeEnum = {
  /**
   * value: "NORMAL"
   * @const
   */
  NORMAL: "NORMAL",

  /**
   * value: "MAINTENANCE"
   * @const
   */
  MAINTENANCE: "MAINTENANCE"
};
/**
 * System mode
 * @member {module:model/MaintenanceMode.SystemModeEnum} systemMode
 */
MaintenanceMode.prototype.systemMode = undefined;

