/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractTrackerItemReference from './AbstractTrackerItemReference';
import TrackerItemRevision from './TrackerItemRevision';

/**
 * The OutgoingTrackerItemAssociation model module.
 * @module model/OutgoingTrackerItemAssociation
 * @version 3.0
 */
export default class OutgoingTrackerItemAssociation extends AbstractTrackerItemReference {
  /**
   * Constructs a new <code>OutgoingTrackerItemAssociation</code>.
   * Association to another item
   * @alias module:model/OutgoingTrackerItemAssociation
   * @class
   * @extends module:model/AbstractTrackerItemReference
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>OutgoingTrackerItemAssociation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutgoingTrackerItemAssociation} obj Optional instance to populate.
   * @return {module:model/OutgoingTrackerItemAssociation} The populated <code>OutgoingTrackerItemAssociation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OutgoingTrackerItemAssociation();
      AbstractTrackerItemReference.constructFromObject(data, obj);
    }
    return obj;
  }
}
