/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OutlineIndex model module.
 * @module model/OutlineIndex
 * @version 3.0
 */
export default class OutlineIndex {
  /**
   * Constructs a new <code>OutlineIndex</code>.
   * Represents the index of an item on a specific outline level.
   * @alias module:model/OutlineIndex
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OutlineIndex</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutlineIndex} obj Optional instance to populate.
   * @return {module:model/OutlineIndex} The populated <code>OutlineIndex</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OutlineIndex();
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'Number');
    }
    return obj;
  }
}

/**
 * Outline index
 * @member {Number} index
 */
OutlineIndex.prototype.index = undefined;

/**
 * Outline level
 * @member {Number} level
 */
OutlineIndex.prototype.level = undefined;

