/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractOutline from './AbstractOutline';
import OutlineIndex from './OutlineIndex';
import TrackerItemReference from './TrackerItemReference';

/**
 * The OutlineItem model module.
 * @module model/OutlineItem
 * @version 3.0
 */
export default class OutlineItem extends AbstractOutline {
  /**
   * Constructs a new <code>OutlineItem</code>.
   * Represents an outline item.
   * @alias module:model/OutlineItem
   * @class
   * @extends module:model/AbstractOutline
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>OutlineItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutlineItem} obj Optional instance to populate.
   * @return {module:model/OutlineItem} The populated <code>OutlineItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OutlineItem();
      AbstractOutline.constructFromObject(data, obj);
      if (data.hasOwnProperty('hasChildren'))
        obj.hasChildren = ApiClient.convertToType(data['hasChildren'], 'Boolean');
      if (data.hasOwnProperty('itemReference'))
        obj.itemReference = TrackerItemReference.constructFromObject(data['itemReference']);
    }
    return obj;
  }
}

/**
 * Indicator if the item has child items.
 * @member {Boolean} hasChildren
 */
OutlineItem.prototype.hasChildren = undefined;

/**
 * @member {module:model/TrackerItemReference} itemReference
 */
OutlineItem.prototype.itemReference = undefined;

