/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RoleReference from './RoleReference';

/**
 * The ProjectMemberPermissions model module.
 * @module model/ProjectMemberPermissions
 * @version 3.0
 */
export default class ProjectMemberPermissions {
  /**
   * Constructs a new <code>ProjectMemberPermissions</code>.
   * Project member permissions
   * @alias module:model/ProjectMemberPermissions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProjectMemberPermissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectMemberPermissions} obj Optional instance to populate.
   * @return {module:model/ProjectMemberPermissions} The populated <code>ProjectMemberPermissions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectMemberPermissions();
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], [RoleReference]);
    }
    return obj;
  }
}

/**
 * Role references
 * @member {Array.<module:model/RoleReference>} roles
 */
ProjectMemberPermissions.prototype.roles = undefined;

