/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProjectFilteringRequest model module.
 * @module model/ProjectFilteringRequest
 * @version 3.0
 */
export default class ProjectFilteringRequest {
  /**
   * Constructs a new <code>ProjectFilteringRequest</code>.
   * @alias module:model/ProjectFilteringRequest
   * @class
   * @param keyName {String} Key name of the project
   */
  constructor(keyName) {
    this.keyName = keyName;
  }

  /**
   * Constructs a <code>ProjectFilteringRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectFilteringRequest} obj Optional instance to populate.
   * @return {module:model/ProjectFilteringRequest} The populated <code>ProjectFilteringRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectFilteringRequest();
      if (data.hasOwnProperty('keyName'))
        obj.keyName = ApiClient.convertToType(data['keyName'], 'String');
    }
    return obj;
  }
}

/**
 * Key name of the project
 * @member {String} keyName
 */
ProjectFilteringRequest.prototype.keyName = undefined;

