/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ReportCell from './ReportCell';
import ReportItemReference from './ReportItemReference';
import ReportReferenceLevel from './ReportReferenceLevel';
import ReportRow from './ReportRow';

/**
 * The ReportReferencedRow model module.
 * @module model/ReportReferencedRow
 * @version 3.0
 */
export default class ReportReferencedRow extends ReportRow {
  /**
   * Constructs a new <code>ReportReferencedRow</code>.
   * Result row having references.
   * @alias module:model/ReportReferencedRow
   * @class
   * @extends module:model/ReportRow
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ReportReferencedRow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReportReferencedRow} obj Optional instance to populate.
   * @return {module:model/ReportReferencedRow} The populated <code>ReportReferencedRow</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReportReferencedRow();
      ReportRow.constructFromObject(data, obj);
      if (data.hasOwnProperty('cells'))
        obj.cells = ApiClient.convertToType(data['cells'], [ReportCell]);
      if (data.hasOwnProperty('isRealResult'))
        obj.isRealResult = ApiClient.convertToType(data['isRealResult'], 'Boolean');
      if (data.hasOwnProperty('itemRef'))
        obj.itemRef = ReportItemReference.constructFromObject(data['itemRef']);
      if (data.hasOwnProperty('outlineLevel'))
        obj.outlineLevel = ApiClient.convertToType(data['outlineLevel'], 'Number');
      if (data.hasOwnProperty('references'))
        obj.references = ReportReferenceLevel.constructFromObject(data['references']);
    }
    return obj;
  }
}

/**
 * Cells in a row.
 * @member {Array.<module:model/ReportCell>} cells
 */
ReportReferencedRow.prototype.cells = undefined;

/**
 * Indicator if the item is a real query result (e.g. not an ancestor item).
 * @member {Boolean} isRealResult
 */
ReportReferencedRow.prototype.isRealResult = undefined;

/**
 * @member {module:model/ReportItemReference} itemRef
 */
ReportReferencedRow.prototype.itemRef = undefined;

/**
 * Item's level in the tracker outline.
 * @member {Number} outlineLevel
 */
ReportReferencedRow.prototype.outlineLevel = undefined;

/**
 * @member {module:model/ReportReferenceLevel} references
 */
ReportReferencedRow.prototype.references = undefined;

