/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FieldReference from './FieldReference';

/**
 * The ResizableReportColumnSettings model module.
 * @module model/ResizableReportColumnSettings
 * @version 3.0
 */
export default class ResizableReportColumnSettings {
  /**
   * Constructs a new <code>ResizableReportColumnSettings</code>.
   * Settings for a resizeable column definition.
   * @alias module:model/ResizableReportColumnSettings
   * @class
   * @param columnIndex {Number} Index of the column in the report table.
   * @param field {module:model/FieldReference} 
   */
  constructor(columnIndex, field) {
    this.columnIndex = columnIndex;
    this.field = field;
  }

  /**
   * Constructs a <code>ResizableReportColumnSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResizableReportColumnSettings} obj Optional instance to populate.
   * @return {module:model/ResizableReportColumnSettings} The populated <code>ResizableReportColumnSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResizableReportColumnSettings();
      if (data.hasOwnProperty('columnIndex'))
        obj.columnIndex = ApiClient.convertToType(data['columnIndex'], 'Number');
      if (data.hasOwnProperty('columnWidthPercentage'))
        obj.columnWidthPercentage = ApiClient.convertToType(data['columnWidthPercentage'], 'Number');
      if (data.hasOwnProperty('field'))
        obj.field = FieldReference.constructFromObject(data['field']);
    }
    return obj;
  }
}

/**
 * Index of the column in the report table.
 * @member {Number} columnIndex
 */
ResizableReportColumnSettings.prototype.columnIndex = undefined;

/**
 * Width of the column in percentage.
 * @member {Number} columnWidthPercentage
 */
ResizableReportColumnSettings.prototype.columnWidthPercentage = undefined;

/**
 * @member {module:model/FieldReference} field
 */
ResizableReportColumnSettings.prototype.field = undefined;

