/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ResourceLockedException model module.
 * @module model/ResourceLockedException
 * @version 3.0
 */
export default class ResourceLockedException {
  /**
   * Constructs a new <code>ResourceLockedException</code>.
   * @alias module:model/ResourceLockedException
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResourceLockedException</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResourceLockedException} obj Optional instance to populate.
   * @return {module:model/ResourceLockedException} The populated <code>ResourceLockedException</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResourceLockedException();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('resourceUri'))
        obj.resourceUri = ApiClient.convertToType(data['resourceUri'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
ResourceLockedException.prototype.message = undefined;

/**
 * @member {String} resourceUri
 */
ResourceLockedException.prototype.resourceUri = undefined;

