/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractFieldValue from './AbstractFieldValue';

/**
 * The TableFieldValue model module.
 * @module model/TableFieldValue
 * @version 3.0
 */
export default class TableFieldValue extends AbstractFieldValue {
  /**
   * Constructs a new <code>TableFieldValue</code>.
   * Value container of a table field
   * @alias module:model/TableFieldValue
   * @class
   * @extends module:model/AbstractFieldValue
   * @param type {} Type of the field
   */
  constructor(type) {
    super(type);
  }

  /**
   * Constructs a <code>TableFieldValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TableFieldValue} obj Optional instance to populate.
   * @return {module:model/TableFieldValue} The populated <code>TableFieldValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TableFieldValue();
      AbstractFieldValue.constructFromObject(data, obj);
      if (data.hasOwnProperty('values'))
        obj.values = ApiClient.convertToType(data['values'], [[AbstractFieldValue]]);
    }
    return obj;
  }
}

/**
 * Table values
 * @member {Array.<Array.<module:model/AbstractFieldValue>>} values
 */
TableFieldValue.prototype.values = undefined;

