/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractField from './AbstractField';
import ChoiceOptionReference from './ChoiceOptionReference';
import SharedFieldReference from './SharedFieldReference';

/**
 * The TrackerChoiceField model module.
 * @module model/TrackerChoiceField
 * @version 3.0
 */
export default class TrackerChoiceField extends AbstractField {
  /**
   * Constructs a new <code>TrackerChoiceField</code>.
   * Tracker type choice field
   * @alias module:model/TrackerChoiceField
   * @class
   * @extends module:model/AbstractField
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TrackerChoiceField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackerChoiceField} obj Optional instance to populate.
   * @return {module:model/TrackerChoiceField} The populated <code>TrackerChoiceField</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackerChoiceField();
      AbstractField.constructFromObject(data, obj);
      if (data.hasOwnProperty('multipleValues'))
        obj.multipleValues = ApiClient.convertToType(data['multipleValues'], 'Boolean');
      if (data.hasOwnProperty('referenceType'))
        obj.referenceType = ApiClient.convertToType(data['referenceType'], 'String');
    }
    return obj;
  }
}

/**
 * Multiple values state of a field
 * @member {Boolean} multipleValues
 */
TrackerChoiceField.prototype.multipleValues = undefined;

/**
 * Type of the contained references
 * @member {String} referenceType
 */
TrackerChoiceField.prototype.referenceType = undefined;

