/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TrackerItem from './TrackerItem';
import TrackerItemReviewExport from './TrackerItemReviewExport';

/**
 * The TrackerItemWithTrackerItemReviewsExport model module.
 * @module model/TrackerItemWithTrackerItemReviewsExport
 * @version 3.0
 */
export default class TrackerItemWithTrackerItemReviewsExport {
  /**
   * Constructs a new <code>TrackerItemWithTrackerItemReviewsExport</code>.
   * A Tracker Item with all of its corresponding Tracker Item Reviews
   * @alias module:model/TrackerItemWithTrackerItemReviewsExport
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackerItemWithTrackerItemReviewsExport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackerItemWithTrackerItemReviewsExport} obj Optional instance to populate.
   * @return {module:model/TrackerItemWithTrackerItemReviewsExport} The populated <code>TrackerItemWithTrackerItemReviewsExport</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackerItemWithTrackerItemReviewsExport();
      if (data.hasOwnProperty('trackerItem'))
        obj.trackerItem = TrackerItem.constructFromObject(data['trackerItem']);
      if (data.hasOwnProperty('trackerItemReviews'))
        obj.trackerItemReviews = ApiClient.convertToType(data['trackerItemReviews'], [TrackerItemReviewExport]);
    }
    return obj;
  }
}

/**
 * @member {module:model/TrackerItem} trackerItem
 */
TrackerItemWithTrackerItemReviewsExport.prototype.trackerItem = undefined;

/**
 * List of Tracker Item Reviews
 * @member {Array.<module:model/TrackerItemReviewExport>} trackerItemReviews
 */
TrackerItemWithTrackerItemReviewsExport.prototype.trackerItemReviews = undefined;

