/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TrackerFieldComputedFieldReference model module.
 * @module model/TrackerFieldComputedFieldReference
 * @version 3.0
 */
export default class TrackerFieldComputedFieldReference {
  /**
   * Constructs a new <code>TrackerFieldComputedFieldReference</code>.
   * Describes the Computed Field Reference configuration.
   * @alias module:model/TrackerFieldComputedFieldReference
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackerFieldComputedFieldReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackerFieldComputedFieldReference} obj Optional instance to populate.
   * @return {module:model/TrackerFieldComputedFieldReference} The populated <code>TrackerFieldComputedFieldReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackerFieldComputedFieldReference();
      if (data.hasOwnProperty('referredFieldId'))
        obj.referredFieldId = ApiClient.convertToType(data['referredFieldId'], 'Number');
      if (data.hasOwnProperty('referredFieldTrackerId'))
        obj.referredFieldTrackerId = ApiClient.convertToType(data['referredFieldTrackerId'], 'Number');
      if (data.hasOwnProperty('referredTrackerId'))
        obj.referredTrackerId = ApiClient.convertToType(data['referredTrackerId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} referredFieldId
 */
TrackerFieldComputedFieldReference.prototype.referredFieldId = undefined;

/**
 * @member {Number} referredFieldTrackerId
 */
TrackerFieldComputedFieldReference.prototype.referredFieldTrackerId = undefined;

/**
 * @member {Number} referredTrackerId
 */
TrackerFieldComputedFieldReference.prototype.referredTrackerId = undefined;

