/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TrackerItemFieldMapping from './TrackerItemFieldMapping';
import TrackerItemFieldMappingPair from './TrackerItemFieldMappingPair';
import TrackerItemFieldMappingPossiblePair from './TrackerItemFieldMappingPossiblePair';

/**
 * The TrackerItemFieldMappingInfo model module.
 * @module model/TrackerItemFieldMappingInfo
 * @version 3.0
 */
export default class TrackerItemFieldMappingInfo {
  /**
   * Constructs a new <code>TrackerItemFieldMappingInfo</code>.
   * Tracker field mapping information.
   * @alias module:model/TrackerItemFieldMappingInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackerItemFieldMappingInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackerItemFieldMappingInfo} obj Optional instance to populate.
   * @return {module:model/TrackerItemFieldMappingInfo} The populated <code>TrackerItemFieldMappingInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackerItemFieldMappingInfo();
      if (data.hasOwnProperty('lostMapping'))
        obj.lostMapping = ApiClient.convertToType(data['lostMapping'], [TrackerItemFieldMapping]);
      if (data.hasOwnProperty('mapping'))
        obj.mapping = ApiClient.convertToType(data['mapping'], [TrackerItemFieldMappingPair]);
      if (data.hasOwnProperty('possibleMapping'))
        obj.possibleMapping = ApiClient.convertToType(data['possibleMapping'], [TrackerItemFieldMappingPossiblePair]);
    }
    return obj;
  }
}

/**
 * No mappable field exists, these fields will be lost
 * @member {Array.<module:model/TrackerItemFieldMapping>} lostMapping
 */
TrackerItemFieldMappingInfo.prototype.lostMapping = undefined;

/**
 * Direct mappable fields
 * @member {Array.<module:model/TrackerItemFieldMappingPair>} mapping
 */
TrackerItemFieldMappingInfo.prototype.mapping = undefined;

/**
 * Not direct mappable fields, but possible mapping exist
 * @member {Array.<module:model/TrackerItemFieldMappingPossiblePair>} possibleMapping
 */
TrackerItemFieldMappingInfo.prototype.possibleMapping = undefined;

