/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractTrackerItemChange from './AbstractTrackerItemChange';
import TrackerItemRevision from './TrackerItemRevision';
import UserReference from './UserReference';

/**
 * The TrackerItemHistoryRevision model module.
 * @module model/TrackerItemHistoryRevision
 * @version 3.0
 */
export default class TrackerItemHistoryRevision {
  /**
   * Constructs a new <code>TrackerItemHistoryRevision</code>.
   * Revision history entry.
   * @alias module:model/TrackerItemHistoryRevision
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TrackerItemHistoryRevision</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackerItemHistoryRevision} obj Optional instance to populate.
   * @return {module:model/TrackerItemHistoryRevision} The populated <code>TrackerItemHistoryRevision</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackerItemHistoryRevision();
      if (data.hasOwnProperty('changes'))
        obj.changes = ApiClient.convertToType(data['changes'], [AbstractTrackerItemChange]);
      if (data.hasOwnProperty('itemRevision'))
        obj.itemRevision = TrackerItemRevision.constructFromObject(data['itemRevision']);
      if (data.hasOwnProperty('modifiedAt'))
        obj.modifiedAt = ApiClient.convertToType(data['modifiedAt'], 'Date');
      if (data.hasOwnProperty('modifiedBy'))
        obj.modifiedBy = UserReference.constructFromObject(data['modifiedBy']);
    }
    return obj;
  }
}

/**
 * Changes happened between the previous and current revision.
 * @member {Array.<module:model/AbstractTrackerItemChange>} changes
 */
TrackerItemHistoryRevision.prototype.changes = undefined;

/**
 * @member {module:model/TrackerItemRevision} itemRevision
 */
TrackerItemHistoryRevision.prototype.itemRevision = undefined;

/**
 * The date when the entity was modified
 * @member {Date} modifiedAt
 */
TrackerItemHistoryRevision.prototype.modifiedAt = undefined;

/**
 * @member {module:model/UserReference} modifiedBy
 */
TrackerItemHistoryRevision.prototype.modifiedBy = undefined;

