/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TraceabilityItem from './TraceabilityItem';

/**
 * The TraceabilityResult model module.
 * @module model/TraceabilityResult
 * @version 3.0
 */
export default class TraceabilityResult {
  /**
   * Constructs a new <code>TraceabilityResult</code>.
   * Traceability result
   * @alias module:model/TraceabilityResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TraceabilityResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TraceabilityResult} obj Optional instance to populate.
   * @return {module:model/TraceabilityResult} The populated <code>TraceabilityResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TraceabilityResult();
      if (data.hasOwnProperty('limitWarnings'))
        obj.limitWarnings = ApiClient.convertToType(data['limitWarnings'], 'String');
      if (data.hasOwnProperty('traceabilityItems'))
        obj.traceabilityItems = ApiClient.convertToType(data['traceabilityItems'], [TraceabilityItem]);
    }
    return obj;
  }
}

/**
 * limit warnings
 * @member {String} limitWarnings
 */
TraceabilityResult.prototype.limitWarnings = undefined;

/**
 * traceability items
 * @member {Array.<module:model/TraceabilityItem>} traceabilityItems
 */
TraceabilityResult.prototype.traceabilityItems = undefined;

