/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractFieldValue from './AbstractFieldValue';
import TableFieldValue from './TableFieldValue';

/**
 * The UpdateTrackerItemField model module.
 * @module model/UpdateTrackerItemField
 * @version 3.0
 */
export default class UpdateTrackerItemField {
  /**
   * Constructs a new <code>UpdateTrackerItemField</code>.
   * Update fields of a tracker item
   * @alias module:model/UpdateTrackerItemField
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateTrackerItemField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateTrackerItemField} obj Optional instance to populate.
   * @return {module:model/UpdateTrackerItemField} The populated <code>UpdateTrackerItemField</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateTrackerItemField();
      if (data.hasOwnProperty('fieldValues'))
        obj.fieldValues = ApiClient.convertToType(data['fieldValues'], [AbstractFieldValue]);
      if (data.hasOwnProperty('tableValues'))
        obj.tableValues = ApiClient.convertToType(data['tableValues'], [TableFieldValue]);
    }
    return obj;
  }
}

/**
 * Fields of a tracker item
 * @member {Array.<module:model/AbstractFieldValue>} fieldValues
 */
UpdateTrackerItemField.prototype.fieldValues = undefined;

/**
 * Fields of a tracker item
 * @member {Array.<module:model/TableFieldValue>} tableValues
 */
UpdateTrackerItemField.prototype.tableValues = undefined;

