/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import User from './User';

/**
 * The UserSearchResult model module.
 * @module model/UserSearchResult
 * @version 3.0
 */
export default class UserSearchResult {
  /**
   * Constructs a new <code>UserSearchResult</code>.
   * Paginated search result of users
   * @alias module:model/UserSearchResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserSearchResult} obj Optional instance to populate.
   * @return {module:model/UserSearchResult} The populated <code>UserSearchResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserSearchResult();
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('users'))
        obj.users = ApiClient.convertToType(data['users'], [User]);
    }
    return obj;
  }
}

/**
 * Index of the page
 * @member {Number} page
 */
UserSearchResult.prototype.page = undefined;

/**
 * Size of the found page
 * @member {Number} pageSize
 */
UserSearchResult.prototype.pageSize = undefined;

/**
 * Number of matched tracker items by the search criteria
 * @member {Number} total
 */
UserSearchResult.prototype.total = undefined;

/**
 * Found users
 * @member {Array.<module:model/User>} users
 */
UserSearchResult.prototype.users = undefined;

