/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import OutlineWiki from './OutlineWiki';

/**
 * The WikiOutlineSearchResult model module.
 * @module model/WikiOutlineSearchResult
 * @version 3.0
 */
export default class WikiOutlineSearchResult {
  /**
   * Constructs a new <code>WikiOutlineSearchResult</code>.
   * Paginated search result of outline wiki pages
   * @alias module:model/WikiOutlineSearchResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WikiOutlineSearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WikiOutlineSearchResult} obj Optional instance to populate.
   * @return {module:model/WikiOutlineSearchResult} The populated <code>WikiOutlineSearchResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WikiOutlineSearchResult();
      if (data.hasOwnProperty('outlineWikiPages'))
        obj.outlineWikiPages = ApiClient.convertToType(data['outlineWikiPages'], [OutlineWiki]);
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }
}

/**
 * Found outline wiki pages
 * @member {Array.<module:model/OutlineWiki>} outlineWikiPages
 */
WikiOutlineSearchResult.prototype.outlineWikiPages = undefined;

/**
 * Index of the page
 * @member {Number} page
 */
WikiOutlineSearchResult.prototype.page = undefined;

/**
 * Size of the found page
 * @member {Number} pageSize
 */
WikiOutlineSearchResult.prototype.pageSize = undefined;

/**
 * Number of matched tracker items by the search criteria
 * @member {Number} total
 */
WikiOutlineSearchResult.prototype.total = undefined;

