/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AbstractBaselineReferenceModel from './AbstractBaselineReferenceModel';

/**
 * The WorkingSetTracker model module.
 * @module model/WorkingSetTracker
 * @version 3.0
 */
export default class WorkingSetTracker {
  /**
   * Constructs a new <code>WorkingSetTracker</code>.
   * Tracker information in Working-Set
   * @alias module:model/WorkingSetTracker
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkingSetTracker</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkingSetTracker} obj Optional instance to populate.
   * @return {module:model/WorkingSetTracker} The populated <code>WorkingSetTracker</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkingSetTracker();
      if (data.hasOwnProperty('baseline'))
        obj.baseline = AbstractBaselineReferenceModel.constructFromObject(data['baseline']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('shared'))
        obj.shared = ApiClient.convertToType(data['shared'], 'Boolean');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/AbstractBaselineReferenceModel} baseline
 */
WorkingSetTracker.prototype.baseline = undefined;

/**
 * Date of creation (Working-Set creation date for shared trackers, the date when the branch was created for included trackers)
 * @member {Date} createdAt
 */
WorkingSetTracker.prototype.createdAt = undefined;

/**
 * Is the Tracker deleted or not
 * @member {Boolean} deleted
 */
WorkingSetTracker.prototype.deleted = undefined;

/**
 * Id of the entity
 * @member {Number} id
 */
WorkingSetTracker.prototype.id = undefined;

/**
 * Name of the entity
 * @member {String} name
 */
WorkingSetTracker.prototype.name = undefined;

/**
 * Shared in Working-Set
 * @member {Boolean} shared
 */
WorkingSetTracker.prototype.shared = undefined;

/**
 * Type of a referenced object
 * @member {String} type
 */
WorkingSetTracker.prototype.type = undefined;

