/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TrackerItemReference from './TrackerItemReference';

/**
 * The WorkingSetItemMapping model module.
 * @module model/WorkingSetItemMapping
 * @version 3.0
 */
export default class WorkingSetItemMapping {
  /**
   * Constructs a new <code>WorkingSetItemMapping</code>.
   * Working-Set Tracker Item mapping object
   * @alias module:model/WorkingSetItemMapping
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkingSetItemMapping</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkingSetItemMapping} obj Optional instance to populate.
   * @return {module:model/WorkingSetItemMapping} The populated <code>WorkingSetItemMapping</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkingSetItemMapping();
      if (data.hasOwnProperty('source'))
        obj.source = TrackerItemReference.constructFromObject(data['source']);
      if (data.hasOwnProperty('target'))
        obj.target = TrackerItemReference.constructFromObject(data['target']);
    }
    return obj;
  }
}

/**
 * @member {module:model/TrackerItemReference} source
 */
WorkingSetItemMapping.prototype.source = undefined;

/**
 * @member {module:model/TrackerItemReference} target
 */
WorkingSetItemMapping.prototype.target = undefined;

