/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import WorkingSetReference from './WorkingSetReference';
import WorkingSetTrackerUpdateRequest from './WorkingSetTrackerUpdateRequest';

/**
 * The WorkingSetUpdateRequest model module.
 * @module model/WorkingSetUpdateRequest
 * @version 3.0
 */
export default class WorkingSetUpdateRequest {
  /**
   * Constructs a new <code>WorkingSetUpdateRequest</code>.
   * @alias module:model/WorkingSetUpdateRequest
   * @class
   * @param source {module:model/WorkingSetReference} 
   * @param target {module:model/WorkingSetReference} 
   */
  constructor(source, target) {
    this.source = source;
    this.target = target;
  }

  /**
   * Constructs a <code>WorkingSetUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkingSetUpdateRequest} obj Optional instance to populate.
   * @return {module:model/WorkingSetUpdateRequest} The populated <code>WorkingSetUpdateRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkingSetUpdateRequest();
      if (data.hasOwnProperty('projectBaselineId'))
        obj.projectBaselineId = ApiClient.convertToType(data['projectBaselineId'], 'Number');
      if (data.hasOwnProperty('source'))
        obj.source = WorkingSetReference.constructFromObject(data['source']);
      if (data.hasOwnProperty('target'))
        obj.target = WorkingSetReference.constructFromObject(data['target']);
      if (data.hasOwnProperty('trackers'))
        obj.trackers = ApiClient.convertToType(data['trackers'], [WorkingSetTrackerUpdateRequest]);
    }
    return obj;
  }
}

/**
 * @member {Number} projectBaselineId
 */
WorkingSetUpdateRequest.prototype.projectBaselineId = undefined;

/**
 * @member {module:model/WorkingSetReference} source
 */
WorkingSetUpdateRequest.prototype.source = undefined;

/**
 * @member {module:model/WorkingSetReference} target
 */
WorkingSetUpdateRequest.prototype.target = undefined;

/**
 * @member {Array.<module:model/WorkingSetTrackerUpdateRequest>} trackers
 */
WorkingSetUpdateRequest.prototype.trackers = undefined;

