/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The WorkingSetMinimal model module.
 * @module model/WorkingSetMinimal
 * @version 3.0
 */
export default class WorkingSetMinimal {
  /**
   * Constructs a new <code>WorkingSetMinimal</code>.
   * Minimal information of a Working-Set
   * @alias module:model/WorkingSetMinimal
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkingSetMinimal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkingSetMinimal} obj Optional instance to populate.
   * @return {module:model/WorkingSetMinimal} The populated <code>WorkingSetMinimal</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkingSetMinimal();
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * The date when the Working-Set was created
 * @member {Date} createdAt
 */
WorkingSetMinimal.prototype.createdAt = undefined;

/**
 * Is the Working-Set deleted or not
 * @member {Boolean} deleted
 */
WorkingSetMinimal.prototype.deleted = undefined;

/**
 * Id of the entity
 * @member {Number} id
 */
WorkingSetMinimal.prototype.id = undefined;

/**
 * Name of the entity
 * @member {String} name
 */
WorkingSetMinimal.prototype.name = undefined;

/**
 * Type of a referenced object
 * @member {String} type
 */
WorkingSetMinimal.prototype.type = undefined;

