/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Association', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.Association();
      });

      it('should create an instance of Association', function() {
        // TODO: update the code to test Association
        expect(instance).to.be.a(CodebeamerSwaggerApi.Association);
      });

      it('should have the property baselineId (base name: "baselineId")', function() {
        // TODO: update the code to test the property baselineId
        expect(instance).to.have.property('baselineId');
        // expect(instance.baselineId).to.be(expectedValueLiteral);
      });

      it('should have the property biDirectionalPropagation (base name: "biDirectionalPropagation")', function() {
        // TODO: update the code to test the property biDirectionalPropagation
        expect(instance).to.have.property('biDirectionalPropagation');
        // expect(instance.biDirectionalPropagation).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property createdBy (base name: "createdBy")', function() {
        // TODO: update the code to test the property createdBy
        expect(instance).to.have.property('createdBy');
        // expect(instance.createdBy).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property descriptionFormat (base name: "descriptionFormat")', function() {
        // TODO: update the code to test the property descriptionFormat
        expect(instance).to.have.property('descriptionFormat');
        // expect(instance.descriptionFormat).to.be(expectedValueLiteral);
      });

      it('should have the property from (base name: "from")', function() {
        // TODO: update the code to test the property from
        expect(instance).to.have.property('from');
        // expect(instance.from).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property propagatingDependencies (base name: "propagatingDependencies")', function() {
        // TODO: update the code to test the property propagatingDependencies
        expect(instance).to.have.property('propagatingDependencies');
        // expect(instance.propagatingDependencies).to.be(expectedValueLiteral);
      });

      it('should have the property propagatingSuspects (base name: "propagatingSuspects")', function() {
        // TODO: update the code to test the property propagatingSuspects
        expect(instance).to.have.property('propagatingSuspects');
        // expect(instance.propagatingSuspects).to.be(expectedValueLiteral);
      });

      it('should have the property reversePropagation (base name: "reversePropagation")', function() {
        // TODO: update the code to test the property reversePropagation
        expect(instance).to.have.property('reversePropagation');
        // expect(instance.reversePropagation).to.be(expectedValueLiteral);
      });

      it('should have the property to (base name: "to")', function() {
        // TODO: update the code to test the property to
        expect(instance).to.have.property('to');
        // expect(instance.to).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

    });
  });

}));
