/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChoiceOptionsChoiceOption', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.ChoiceOptionsChoiceOption();
      });

      it('should create an instance of ChoiceOptionsChoiceOption', function() {
        // TODO: update the code to test ChoiceOptionsChoiceOption
        expect(instance).to.be.a(CodebeamerSwaggerApi.ChoiceOptionsChoiceOption);
      });

      it('should have the property color (base name: "color")', function() {
        // TODO: update the code to test the property color
        expect(instance).to.have.property('color');
        // expect(instance.color).to.be(expectedValueLiteral);
      });

      it('should have the property defaultInStatuses (base name: "defaultInStatuses")', function() {
        // TODO: update the code to test the property defaultInStatuses
        expect(instance).to.have.property('defaultInStatuses');
        // expect(instance.defaultInStatuses).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property meanings (base name: "meanings")', function() {
        // TODO: update the code to test the property meanings
        expect(instance).to.have.property('meanings');
        // expect(instance.meanings).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property restrictedToStatuses (base name: "restrictedToStatuses")', function() {
        // TODO: update the code to test the property restrictedToStatuses
        expect(instance).to.have.property('restrictedToStatuses');
        // expect(instance.restrictedToStatuses).to.be(expectedValueLiteral);
      });

    });
  });

}));
