/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateTestRunFromTestSetsRequest', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.CreateTestRunFromTestSetsRequest();
      });

      it('should create an instance of CreateTestRunFromTestSetsRequest', function() {
        // TODO: update the code to test CreateTestRunFromTestSetsRequest
        expect(instance).to.be.a(CodebeamerSwaggerApi.CreateTestRunFromTestSetsRequest);
      });

      it('should have the property runOnlyAcceptedTestCases (base name: "runOnlyAcceptedTestCases")', function() {
        // TODO: update the code to test the property runOnlyAcceptedTestCases
        expect(instance).to.have.property('runOnlyAcceptedTestCases');
        // expect(instance.runOnlyAcceptedTestCases).to.be(expectedValueLiteral);
      });

      it('should have the property testRunModel (base name: "testRunModel")', function() {
        // TODO: update the code to test the property testRunModel
        expect(instance).to.have.property('testRunModel');
        // expect(instance.testRunModel).to.be(expectedValueLiteral);
      });

      it('should have the property testSetRefs (base name: "testSetRefs")', function() {
        // TODO: update the code to test the property testSetRefs
        expect(instance).to.have.property('testSetRefs');
        // expect(instance.testSetRefs).to.be(expectedValueLiteral);
      });

    });
  });

}));
