/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeploymentModel', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.DeploymentModel();
      });

      it('should create an instance of DeploymentModel', function() {
        // TODO: update the code to test DeploymentModel
        expect(instance).to.be.a(CodebeamerSwaggerApi.DeploymentModel);
      });

      it('should have the property importTrackerHierarchy (base name: "importTrackerHierarchy")', function() {
        // TODO: update the code to test the property importTrackerHierarchy
        expect(instance).to.have.property('importTrackerHierarchy');
        // expect(instance.importTrackerHierarchy).to.be(expectedValueLiteral);
      });

      it('should have the property imports (base name: "imports")', function() {
        // TODO: update the code to test the property imports
        expect(instance).to.have.property('imports');
        // expect(instance.imports).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property skipRefreshComputedFields (base name: "skipRefreshComputedFields")', function() {
        // TODO: update the code to test the property skipRefreshComputedFields
        expect(instance).to.have.property('skipRefreshComputedFields');
        // expect(instance.skipRefreshComputedFields).to.be(expectedValueLiteral);
      });

    });
  });

}));
