/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeployProject', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.DeployProject();
      });

      it('should create an instance of DeployProject', function() {
        // TODO: update the code to test DeployProject
        expect(instance).to.be.a(CodebeamerSwaggerApi.DeployProject);
      });

      it('should have the property configurationFileId (base name: "configurationFileId")', function() {
        // TODO: update the code to test the property configurationFileId
        expect(instance).to.have.property('configurationFileId');
        // expect(instance.configurationFileId).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property project (base name: "project")', function() {
        // TODO: update the code to test the property project
        expect(instance).to.have.property('project');
        // expect(instance.project).to.be(expectedValueLiteral);
      });

      it('should have the property projectFileId (base name: "projectFileId")', function() {
        // TODO: update the code to test the property projectFileId
        expect(instance).to.have.property('projectFileId');
        // expect(instance.projectFileId).to.be(expectedValueLiteral);
      });

    });
  });

}));
