/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PaginatedAuditPermissionsResponse', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.PaginatedAuditPermissionsResponse();
      });

      it('should create an instance of PaginatedAuditPermissionsResponse', function() {
        // TODO: update the code to test PaginatedAuditPermissionsResponse
        expect(instance).to.be.a(CodebeamerSwaggerApi.PaginatedAuditPermissionsResponse);
      });

      it('should have the property auditPermissions (base name: "auditPermissions")', function() {
        // TODO: update the code to test the property auditPermissions
        expect(instance).to.have.property('auditPermissions');
        // expect(instance.auditPermissions).to.be(expectedValueLiteral);
      });

      it('should have the property nextLink (base name: "nextLink")', function() {
        // TODO: update the code to test the property nextLink
        expect(instance).to.have.property('nextLink');
        // expect(instance.nextLink).to.be(expectedValueLiteral);
      });

      it('should have the property page (base name: "page")', function() {
        // TODO: update the code to test the property page
        expect(instance).to.have.property('page');
        // expect(instance.page).to.be(expectedValueLiteral);
      });

      it('should have the property pageSize (base name: "pageSize")', function() {
        // TODO: update the code to test the property pageSize
        expect(instance).to.have.property('pageSize');
        // expect(instance.pageSize).to.be(expectedValueLiteral);
      });

      it('should have the property previousLink (base name: "previousLink")', function() {
        // TODO: update the code to test the property previousLink
        expect(instance).to.have.property('previousLink');
        // expect(instance.previousLink).to.be(expectedValueLiteral);
      });

      it('should have the property total (base name: "total")', function() {
        // TODO: update the code to test the property total
        expect(instance).to.have.property('total');
        // expect(instance.total).to.be(expectedValueLiteral);
      });

    });
  });

}));
