/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ReportReferenceLevelSettings', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.ReportReferenceLevelSettings();
      });

      it('should create an instance of ReportReferenceLevelSettings', function() {
        // TODO: update the code to test ReportReferenceLevelSettings
        expect(instance).to.be.a(CodebeamerSwaggerApi.ReportReferenceLevelSettings);
      });

      it('should have the property columns (base name: "columns")', function() {
        // TODO: update the code to test the property columns
        expect(instance).to.have.property('columns');
        // expect(instance.columns).to.be(expectedValueLiteral);
      });

      it('should have the property downstreamReference (base name: "downstreamReference")', function() {
        // TODO: update the code to test the property downstreamReference
        expect(instance).to.have.property('downstreamReference');
        // expect(instance.downstreamReference).to.be(expectedValueLiteral);
      });

      it('should have the property level (base name: "level")', function() {
        // TODO: update the code to test the property level
        expect(instance).to.have.property('level');
        // expect(instance.level).to.be(expectedValueLiteral);
      });

      it('should have the property referenceTrackerTypes (base name: "referenceTrackerTypes")', function() {
        // TODO: update the code to test the property referenceTrackerTypes
        expect(instance).to.have.property('referenceTrackerTypes');
        // expect(instance.referenceTrackerTypes).to.be(expectedValueLiteral);
      });

      it('should have the property referenceTrackers (base name: "referenceTrackers")', function() {
        // TODO: update the code to test the property referenceTrackers
        expect(instance).to.have.property('referenceTrackers');
        // expect(instance.referenceTrackers).to.be(expectedValueLiteral);
      });

      it('should have the property upstreamReference (base name: "upstreamReference")', function() {
        // TODO: update the code to test the property upstreamReference
        expect(instance).to.have.property('upstreamReference');
        // expect(instance.upstreamReference).to.be(expectedValueLiteral);
      });

    });
  });

}));
