/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ReportColumn', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.ReportColumn();
      });

      it('should create an instance of ReportColumn', function() {
        // TODO: update the code to test ReportColumn
        expect(instance).to.be.a(CodebeamerSwaggerApi.ReportColumn);
      });

      it('should have the property columnIndex (base name: "columnIndex")', function() {
        // TODO: update the code to test the property columnIndex
        expect(instance).to.have.property('columnIndex');
        // expect(instance.columnIndex).to.be(expectedValueLiteral);
      });

      it('should have the property columnRef (base name: "columnRef")', function() {
        // TODO: update the code to test the property columnRef
        expect(instance).to.have.property('columnRef');
        // expect(instance.columnRef).to.be(expectedValueLiteral);
      });

      it('should have the property columnWidthPercentage (base name: "columnWidthPercentage")', function() {
        // TODO: update the code to test the property columnWidthPercentage
        expect(instance).to.have.property('columnWidthPercentage');
        // expect(instance.columnWidthPercentage).to.be(expectedValueLiteral);
      });

      it('should have the property field (base name: "field")', function() {
        // TODO: update the code to test the property field
        expect(instance).to.have.property('field');
        // expect(instance.field).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
