/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TrackerFieldLayoutSettings', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.TrackerFieldLayoutSettings();
      });

      it('should create an instance of TrackerFieldLayoutSettings', function() {
        // TODO: update the code to test TrackerFieldLayoutSettings
        expect(instance).to.be.a(CodebeamerSwaggerApi.TrackerFieldLayoutSettings);
      });

      it('should have the property defaultLayout (base name: "defaultLayout")', function() {
        // TODO: update the code to test the property defaultLayout
        expect(instance).to.have.property('defaultLayout');
        // expect(instance.defaultLayout).to.be(expectedValueLiteral);
      });

      it('should have the property layouts (base name: "layouts")', function() {
        // TODO: update the code to test the property layouts
        expect(instance).to.have.property('layouts');
        // expect(instance.layouts).to.be(expectedValueLiteral);
      });

      it('should have the property statusLayout (base name: "statusLayout")', function() {
        // TODO: update the code to test the property statusLayout
        expect(instance).to.have.property('statusLayout');
        // expect(instance.statusLayout).to.be(expectedValueLiteral);
      });

    });
  });

}));
