/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TrackerTree', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.TrackerTree();
      });

      it('should create an instance of TrackerTree', function() {
        // TODO: update the code to test TrackerTree
        expect(instance).to.be.a(CodebeamerSwaggerApi.TrackerTree);
      });

      it('should have the property children (base name: "children")', function() {
        // TODO: update the code to test the property children
        expect(instance).to.have.property('children');
        // expect(instance.children).to.be(expectedValueLiteral);
      });

      it('should have the property isFolder (base name: "isFolder")', function() {
        // TODO: update the code to test the property isFolder
        expect(instance).to.have.property('isFolder');
        // expect(instance.isFolder).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property trackerId (base name: "trackerId")', function() {
        // TODO: update the code to test the property trackerId
        expect(instance).to.have.property('trackerId');
        // expect(instance.trackerId).to.be(expectedValueLiteral);
      });

    });
  });

}));
