/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TraceabilityResult', function() {
      beforeEach(function() {
        instance = new CodebeamerSwaggerApi.TraceabilityResult();
      });

      it('should create an instance of TraceabilityResult', function() {
        // TODO: update the code to test TraceabilityResult
        expect(instance).to.be.a(CodebeamerSwaggerApi.TraceabilityResult);
      });

      it('should have the property limitWarnings (base name: "limitWarnings")', function() {
        // TODO: update the code to test the property limitWarnings
        expect(instance).to.have.property('limitWarnings');
        // expect(instance.limitWarnings).to.be(expectedValueLiteral);
      });

      it('should have the property traceabilityItems (base name: "traceabilityItems")', function() {
        // TODO: update the code to test the property traceabilityItems
        expect(instance).to.have.property('traceabilityItems');
        // expect(instance.traceabilityItems).to.be(expectedValueLiteral);
      });

    });
  });

}));
