/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AbstractBackgroundJobStatusInfo from './model/AbstractBackgroundJobStatusInfo';
import AbstractBaselineReferenceModel from './model/AbstractBaselineReferenceModel';
import AbstractField from './model/AbstractField';
import AbstractFieldValue from './model/AbstractFieldValue';
import AbstractOutline from './model/AbstractOutline';
import AbstractReference from './model/AbstractReference';
import AbstractTrackerItemChange from './model/AbstractTrackerItemChange';
import AbstractTrackerItemReference from './model/AbstractTrackerItemReference';
import AccessPermission from './model/AccessPermission';
import AccessPermissionsRequest from './model/AccessPermissionsRequest';
import ArtifactReference from './model/ArtifactReference';
import ArtifactReferenceField from './model/ArtifactReferenceField';
import ArtifactRevision from './model/ArtifactRevision';
import ArtifactRevisionSearchResult from './model/ArtifactRevisionSearchResult';
import Association from './model/Association';
import AssociationType from './model/AssociationType';
import AssociationTypeReference from './model/AssociationTypeReference';
import Attachment from './model/Attachment';
import AttachmentMigrationRequest from './model/AttachmentMigrationRequest';
import AttachmentReference from './model/AttachmentReference';
import AttachmentSearchResult from './model/AttachmentSearchResult';
import AuditPermissionMessage from './model/AuditPermissionMessage';
import AuditPermissions from './model/AuditPermissions';
import AuditPermissionsRequest from './model/AuditPermissionsRequest';
import AutoApplyTestStepReuses from './model/AutoApplyTestStepReuses';
import AutomatedTestCaseRunResult from './model/AutomatedTestCaseRunResult';
import AutomatedTestRunRequest from './model/AutomatedTestRunRequest';
import BackgroundJob from './model/BackgroundJob';
import BackgroundJobStep from './model/BackgroundJobStep';
import BadRequestException from './model/BadRequestException';
import BaseTrackerFieldChoiceOption from './model/BaseTrackerFieldChoiceOption';
import BaseTrackerFieldPermission from './model/BaseTrackerFieldPermission';
import Baseline from './model/Baseline';
import BatchGetTrackerItemReviewsRequest from './model/BatchGetTrackerItemReviewsRequest';
import BoolField from './model/BoolField';
import BoolFieldValue from './model/BoolFieldValue';
import BranchReference from './model/BranchReference';
import BulkOperationResponse from './model/BulkOperationResponse';
import ChoiceDocuments from './model/ChoiceDocuments';
import ChoiceFieldMultiValue from './model/ChoiceFieldMultiValue';
import ChoiceFieldValue from './model/ChoiceFieldValue';
import ChoiceMembers from './model/ChoiceMembers';
import ChoiceOptionReference from './model/ChoiceOptionReference';
import ChoiceOptions from './model/ChoiceOptions';
import ChoiceOptionsChoiceOption from './model/ChoiceOptionsChoiceOption';
import ChoiceProjects from './model/ChoiceProjects';
import ChoiceRepositories from './model/ChoiceRepositories';
import ChoiceTrackers from './model/ChoiceTrackers';
import ChoiceUsers from './model/ChoiceUsers';
import ChoiceWorkConfigItems from './model/ChoiceWorkConfigItems';
import ColorField from './model/ColorField';
import ColorFieldValue from './model/ColorFieldValue';
import Comment from './model/Comment';
import CommentReference from './model/CommentReference';
import CountryField from './model/CountryField';
import CountryFieldMultiValue from './model/CountryFieldMultiValue';
import CountryFieldValue from './model/CountryFieldValue';
import CreateBaselineRequest from './model/CreateBaselineRequest';
import CreateTestRunFromTestSetsRequest from './model/CreateTestRunFromTestSetsRequest';
import CreateTestRunRequest from './model/CreateTestRunRequest';
import CrossProjectDependency from './model/CrossProjectDependency';
import DateField from './model/DateField';
import DateFieldValue from './model/DateFieldValue';
import DecimalField from './model/DecimalField';
import DecimalFieldValue from './model/DecimalFieldValue';
import DefaultBackgroundJobStatusInfo from './model/DefaultBackgroundJobStatusInfo';
import DefaultFieldSingleValue from './model/DefaultFieldSingleValue';
import DefaultMultiFieldValue from './model/DefaultMultiFieldValue';
import DependencyAttribute from './model/DependencyAttribute';
import DependencyEntityReference from './model/DependencyEntityReference';
import DependencyFinderJobStatusInfo from './model/DependencyFinderJobStatusInfo';
import DeployProject from './model/DeployProject';
import DeploymentModel from './model/DeploymentModel';
import DeploymentProjectExportSettings from './model/DeploymentProjectExportSettings';
import DeploymentTrackerExportSettings from './model/DeploymentTrackerExportSettings';
import DownstreamTrackerItemReference from './model/DownstreamTrackerItemReference';
import DurationField from './model/DurationField';
import DurationFieldValue from './model/DurationFieldValue';
import EditComment from './model/EditComment';
import ExportForDeploymentRequest from './model/ExportForDeploymentRequest';
import ExportProject from './model/ExportProject';
import ExportToWordRequest from './model/ExportToWordRequest';
import ExternalScmRepositoryRequest from './model/ExternalScmRepositoryRequest';
import FailedOperation from './model/FailedOperation';
import FieldLayoutGroups from './model/FieldLayoutGroups';
import FieldLayoutSettings from './model/FieldLayoutSettings';
import FieldReference from './model/FieldReference';
import IncomingTrackerItemAssociation from './model/IncomingTrackerItemAssociation';
import IntegerField from './model/IntegerField';
import IntegerFieldValue from './model/IntegerFieldValue';
import InternalServerErrorException from './model/InternalServerErrorException';
import InvalidParametersException from './model/InvalidParametersException';
import JobReference from './model/JobReference';
import JsonView from './model/JsonView';
import Label from './model/Label';
import LanguageField from './model/LanguageField';
import LanguageFieldMultiValue from './model/LanguageFieldMultiValue';
import LanguageFieldValue from './model/LanguageFieldValue';
import LayoutField from './model/LayoutField';
import LockInfo from './model/LockInfo';
import LockRequest from './model/LockRequest';
import MaintenanceMode from './model/MaintenanceMode';
import MaintenanceModeProperties from './model/MaintenanceModeProperties';
import MemberField from './model/MemberField';
import MemberReferenceSearchResult from './model/MemberReferenceSearchResult';
import NotImplementedException from './model/NotImplementedException';
import NotSupportedFieldValue from './model/NotSupportedFieldValue';
import OptionChoiceField from './model/OptionChoiceField';
import OutgoingTrackerItemAssociation from './model/OutgoingTrackerItemAssociation';
import OutlineIndex from './model/OutlineIndex';
import OutlineItem from './model/OutlineItem';
import OutlineItemSearchResult from './model/OutlineItemSearchResult';
import OutlineWiki from './model/OutlineWiki';
import PaginatedAuditPermissionsResponse from './model/PaginatedAuditPermissionsResponse';
import PerStatusFieldPermission from './model/PerStatusFieldPermission';
import PermissionIdsRequest from './model/PermissionIdsRequest';
import PostComment from './model/PostComment';
import Project from './model/Project';
import ProjectBaselineReference from './model/ProjectBaselineReference';
import ProjectChoiceField from './model/ProjectChoiceField';
import ProjectFilteringRequest from './model/ProjectFilteringRequest';
import ProjectMemberPermissions from './model/ProjectMemberPermissions';
import ProjectReference from './model/ProjectReference';
import ProjectRoleReference from './model/ProjectRoleReference';
import ProjectSearchResult from './model/ProjectSearchResult';
import ProjectWithTrackerTypesReference from './model/ProjectWithTrackerTypesReference';
import ReferenceField from './model/ReferenceField';
import ReferenceFilterBasedChoiceReferenceFilter from './model/ReferenceFilterBasedChoiceReferenceFilter';
import ReferenceSearchResult from './model/ReferenceSearchResult';
import ReferredTestStepFieldValue from './model/ReferredTestStepFieldValue';
import RemoteMigrationFile from './model/RemoteMigrationFile';
import ReportAggregate from './model/ReportAggregate';
import ReportCell from './model/ReportCell';
import ReportColumn from './model/ReportColumn';
import ReportColumnSettings from './model/ReportColumnSettings';
import ReportGroup from './model/ReportGroup';
import ReportGroupWithGroups from './model/ReportGroupWithGroups';
import ReportGroupWithReferencedRows from './model/ReportGroupWithReferencedRows';
import ReportGroupWithRows from './model/ReportGroupWithRows';
import ReportItem from './model/ReportItem';
import ReportItemReference from './model/ReportItemReference';
import ReportItemResult from './model/ReportItemResult';
import ReportPagingInformation from './model/ReportPagingInformation';
import ReportPermission from './model/ReportPermission';
import ReportReference from './model/ReportReference';
import ReportReferenceLevel from './model/ReportReferenceLevel';
import ReportReferenceLevelSettings from './model/ReportReferenceLevelSettings';
import ReportReferencedRow from './model/ReportReferencedRow';
import ReportResult from './model/ReportResult';
import ReportRow from './model/ReportRow';
import RepositoryChoiceField from './model/RepositoryChoiceField';
import RepositoryReference from './model/RepositoryReference';
import ResizableReportColumnSettings from './model/ResizableReportColumnSettings';
import ResourceForbiddenException from './model/ResourceForbiddenException';
import ResourceLockedException from './model/ResourceLockedException';
import ResourceNotFoundException from './model/ResourceNotFoundException';
import ResourceUnauthorizedException from './model/ResourceUnauthorizedException';
import RestException from './model/RestException';
import ReviewMemberReferenceField from './model/ReviewMemberReferenceField';
import Role from './model/Role';
import RoleReference from './model/RoleReference';
import RoleWithPermissions from './model/RoleWithPermissions';
import SameAsFieldPermission from './model/SameAsFieldPermission';
import SharedFieldReference from './model/SharedFieldReference';
import SimpleReportSettings from './model/SimpleReportSettings';
import SingleFieldPermission from './model/SingleFieldPermission';
import StatusLayout from './model/StatusLayout';
import SystemStatus from './model/SystemStatus';
import TableField from './model/TableField';
import TableFieldValue from './model/TableFieldValue';
import TestRunResult from './model/TestRunResult';
import TextField from './model/TextField';
import TextFieldValue from './model/TextFieldValue';
import TooManyRequestsException from './model/TooManyRequestsException';
import TraceabilityInitialLevelFilter from './model/TraceabilityInitialLevelFilter';
import TraceabilityItem from './model/TraceabilityItem';
import TraceabilityLevelFilter from './model/TraceabilityLevelFilter';
import TraceabilityResult from './model/TraceabilityResult';
import Tracker from './model/Tracker';
import TrackerBaselineReference from './model/TrackerBaselineReference';
import TrackerBasicInformation from './model/TrackerBasicInformation';
import TrackerChoiceField from './model/TrackerChoiceField';
import TrackerConfiguration from './model/TrackerConfiguration';
import TrackerField from './model/TrackerField';
import TrackerFieldComputedFieldReference from './model/TrackerFieldComputedFieldReference';
import TrackerFieldDateFieldSettings from './model/TrackerFieldDateFieldSettings';
import TrackerFieldDependency from './model/TrackerFieldDependency';
import TrackerFieldLayoutSettings from './model/TrackerFieldLayoutSettings';
import TrackerFieldPermissionAccessPermission from './model/TrackerFieldPermissionAccessPermission';
import TrackerFieldPermissions from './model/TrackerFieldPermissions';
import TrackerFieldServiceDeskField from './model/TrackerFieldServiceDeskField';
import TrackerFieldStatusPermissions from './model/TrackerFieldStatusPermissions';
import TrackerFieldsStatusPermissions from './model/TrackerFieldsStatusPermissions';
import TrackerFilteringRequest from './model/TrackerFilteringRequest';
import TrackerIdIconBody from './model/TrackerIdIconBody';
import TrackerItem from './model/TrackerItem';
import TrackerItemAttachmentRequest from './model/TrackerItemAttachmentRequest';
import TrackerItemChange from './model/TrackerItemChange';
import TrackerItemChildReference from './model/TrackerItemChildReference';
import TrackerItemChoiceField from './model/TrackerItemChoiceField';
import TrackerItemField from './model/TrackerItemField';
import TrackerItemFieldAccessibility from './model/TrackerItemFieldAccessibility';
import TrackerItemFieldAccessibilityList from './model/TrackerItemFieldAccessibilityList';
import TrackerItemFieldMapping from './model/TrackerItemFieldMapping';
import TrackerItemFieldMappingInfo from './model/TrackerItemFieldMappingInfo';
import TrackerItemFieldMappingPair from './model/TrackerItemFieldMappingPair';
import TrackerItemFieldMappingPossiblePair from './model/TrackerItemFieldMappingPossiblePair';
import TrackerItemHistory from './model/TrackerItemHistory';
import TrackerItemHistoryRevision from './model/TrackerItemHistoryRevision';
import TrackerItemMoveRequest from './model/TrackerItemMoveRequest';
import TrackerItemReference from './model/TrackerItemReference';
import TrackerItemReferenceData from './model/TrackerItemReferenceData';
import TrackerItemReferenceSearchResult from './model/TrackerItemReferenceSearchResult';
import TrackerItemRelationsResult from './model/TrackerItemRelationsResult';
import TrackerItemReview from './model/TrackerItemReview';
import TrackerItemReviewConfig from './model/TrackerItemReviewConfig';
import TrackerItemReviewExport from './model/TrackerItemReviewExport';
import TrackerItemReviewVote from './model/TrackerItemReviewVote';
import TrackerItemReviewVoteExport from './model/TrackerItemReviewVoteExport';
import TrackerItemRevision from './model/TrackerItemRevision';
import TrackerItemRowChange from './model/TrackerItemRowChange';
import TrackerItemSearchRequest from './model/TrackerItemSearchRequest';
import TrackerItemSearchResult from './model/TrackerItemSearchResult';
import TrackerItemWithTrackerItemReviewsExport from './model/TrackerItemWithTrackerItemReviewsExport';
import TrackerItemsRequest from './model/TrackerItemsRequest';
import TrackerPermission from './model/TrackerPermission';
import TrackerPermissionReference from './model/TrackerPermissionReference';
import TrackerReference from './model/TrackerReference';
import TrackerReportSettings from './model/TrackerReportSettings';
import TrackerSearchResult from './model/TrackerSearchResult';
import TrackerTree from './model/TrackerTree';
import TrackerType from './model/TrackerType';
import TrackerTypeReference from './model/TrackerTypeReference';
import TrackerWorkingSet from './model/TrackerWorkingSet';
import UnrestrictedFieldPermission from './model/UnrestrictedFieldPermission';
import UpdateAttachment from './model/UpdateAttachment';
import UpdateTestCaseRunRequest from './model/UpdateTestCaseRunRequest';
import UpdateTestRunRequest from './model/UpdateTestRunRequest';
import UpdateTrackerItemChildrenRequest from './model/UpdateTrackerItemChildrenRequest';
import UpdateTrackerItemField from './model/UpdateTrackerItemField';
import UpdateTrackerItemFieldWithItemId from './model/UpdateTrackerItemFieldWithItemId';
import UpdateTrackerItemTableField from './model/UpdateTrackerItemTableField';
import UploadAttachment from './model/UploadAttachment';
import UpstreamTrackerItemReference from './model/UpstreamTrackerItemReference';
import UrlField from './model/UrlField';
import UrlFieldValue from './model/UrlFieldValue';
import User from './model/User';
import UserChoiceField from './model/UserChoiceField';
import UserFilteringRequest from './model/UserFilteringRequest';
import UserGroup from './model/UserGroup';
import UserGroupReference from './model/UserGroupReference';
import UserReference from './model/UserReference';
import UserReferenceSearchResult from './model/UserReferenceSearchResult';
import UserSearchResult from './model/UserSearchResult';
import WikiOutlineSearchResult from './model/WikiOutlineSearchResult';
import WikiPage from './model/WikiPage';
import WikiPageReference from './model/WikiPageReference';
import WikiRenderRequest from './model/WikiRenderRequest';
import WikiTextField from './model/WikiTextField';
import WikiTextFieldMultiValue from './model/WikiTextFieldMultiValue';
import WikiTextFieldValue from './model/WikiTextFieldValue';
import WorkflowTransition from './model/WorkflowTransition';
import WorkingSetInformation from './model/WorkingSetInformation';
import WorkingSetItemMapping from './model/WorkingSetItemMapping';
import WorkingSetItemsMappingRequest from './model/WorkingSetItemsMappingRequest';
import WorkingSetMinimal from './model/WorkingSetMinimal';
import WorkingSetPermissionRequest from './model/WorkingSetPermissionRequest';
import WorkingSetReference from './model/WorkingSetReference';
import WorkingSetTracker from './model/WorkingSetTracker';
import WorkingSetTrackerUpdateRequest from './model/WorkingSetTrackerUpdateRequest';
import WorkingSetUpdateRequest from './model/WorkingSetUpdateRequest';
import AssociationApi from './api/AssociationApi';
import AttachmentApi from './api/AttachmentApi';
import BackgroundJobApi from './api/BackgroundJobApi';
import BaselineApi from './api/BaselineApi';
import BranchesApi from './api/BranchesApi';
import DeploymentApi from './api/DeploymentApi';
import ExportApi from './api/ExportApi';
import GroupApi from './api/GroupApi';
import MigrationApi from './api/MigrationApi';
import ProjectApi from './api/ProjectApi';
import ReportApi from './api/ReportApi';
import RepositoryItemApi from './api/RepositoryItemApi';
import RoleApi from './api/RoleApi';
import SystemApi from './api/SystemApi';
import SystemAdministratorApi from './api/SystemAdministratorApi';
import TestManagementApi from './api/TestManagementApi';
import TestRunApi from './api/TestRunApi';
import TraceabilityApi from './api/TraceabilityApi';
import TrackerApi from './api/TrackerApi';
import TrackerItemApi from './api/TrackerItemApi';
import TrackerItemMoveApi from './api/TrackerItemMoveApi';
import TrackerItemsAttachmentApi from './api/TrackerItemsAttachmentApi';
import TrackerItemsCommentApi from './api/TrackerItemsCommentApi';
import TrackerPermissionApi from './api/TrackerPermissionApi';
import TrackerReportApi from './api/TrackerReportApi';
import TrackerTreeApi from './api/TrackerTreeApi';
import UserApi from './api/UserApi';
import WikiApi from './api/WikiApi';
import WikisCommentApi from './api/WikisCommentApi';
import WorkingSetApi from './api/WorkingSetApi';
import WorkingSetPermissionApi from './api/WorkingSetPermissionApi';

/**
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CodebeamerSwaggerApi = require('index'); // See note below*.
* var xxxSvc = new CodebeamerSwaggerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CodebeamerSwaggerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CodebeamerSwaggerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CodebeamerSwaggerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AbstractBackgroundJobStatusInfo model constructor.
     * @property {module:model/AbstractBackgroundJobStatusInfo}
     */
    AbstractBackgroundJobStatusInfo,

    /**
     * The AbstractBaselineReferenceModel model constructor.
     * @property {module:model/AbstractBaselineReferenceModel}
     */
    AbstractBaselineReferenceModel,

    /**
     * The AbstractField model constructor.
     * @property {module:model/AbstractField}
     */
    AbstractField,

    /**
     * The AbstractFieldValue model constructor.
     * @property {module:model/AbstractFieldValue}
     */
    AbstractFieldValue,

    /**
     * The AbstractOutline model constructor.
     * @property {module:model/AbstractOutline}
     */
    AbstractOutline,

    /**
     * The AbstractReference model constructor.
     * @property {module:model/AbstractReference}
     */
    AbstractReference,

    /**
     * The AbstractTrackerItemChange model constructor.
     * @property {module:model/AbstractTrackerItemChange}
     */
    AbstractTrackerItemChange,

    /**
     * The AbstractTrackerItemReference model constructor.
     * @property {module:model/AbstractTrackerItemReference}
     */
    AbstractTrackerItemReference,

    /**
     * The AccessPermission model constructor.
     * @property {module:model/AccessPermission}
     */
    AccessPermission,

    /**
     * The AccessPermissionsRequest model constructor.
     * @property {module:model/AccessPermissionsRequest}
     */
    AccessPermissionsRequest,

    /**
     * The ArtifactReference model constructor.
     * @property {module:model/ArtifactReference}
     */
    ArtifactReference,

    /**
     * The ArtifactReferenceField model constructor.
     * @property {module:model/ArtifactReferenceField}
     */
    ArtifactReferenceField,

    /**
     * The ArtifactRevision model constructor.
     * @property {module:model/ArtifactRevision}
     */
    ArtifactRevision,

    /**
     * The ArtifactRevisionSearchResult model constructor.
     * @property {module:model/ArtifactRevisionSearchResult}
     */
    ArtifactRevisionSearchResult,

    /**
     * The Association model constructor.
     * @property {module:model/Association}
     */
    Association,

    /**
     * The AssociationType model constructor.
     * @property {module:model/AssociationType}
     */
    AssociationType,

    /**
     * The AssociationTypeReference model constructor.
     * @property {module:model/AssociationTypeReference}
     */
    AssociationTypeReference,

    /**
     * The Attachment model constructor.
     * @property {module:model/Attachment}
     */
    Attachment,

    /**
     * The AttachmentMigrationRequest model constructor.
     * @property {module:model/AttachmentMigrationRequest}
     */
    AttachmentMigrationRequest,

    /**
     * The AttachmentReference model constructor.
     * @property {module:model/AttachmentReference}
     */
    AttachmentReference,

    /**
     * The AttachmentSearchResult model constructor.
     * @property {module:model/AttachmentSearchResult}
     */
    AttachmentSearchResult,

    /**
     * The AuditPermissionMessage model constructor.
     * @property {module:model/AuditPermissionMessage}
     */
    AuditPermissionMessage,

    /**
     * The AuditPermissions model constructor.
     * @property {module:model/AuditPermissions}
     */
    AuditPermissions,

    /**
     * The AuditPermissionsRequest model constructor.
     * @property {module:model/AuditPermissionsRequest}
     */
    AuditPermissionsRequest,

    /**
     * The AutoApplyTestStepReuses model constructor.
     * @property {module:model/AutoApplyTestStepReuses}
     */
    AutoApplyTestStepReuses,

    /**
     * The AutomatedTestCaseRunResult model constructor.
     * @property {module:model/AutomatedTestCaseRunResult}
     */
    AutomatedTestCaseRunResult,

    /**
     * The AutomatedTestRunRequest model constructor.
     * @property {module:model/AutomatedTestRunRequest}
     */
    AutomatedTestRunRequest,

    /**
     * The BackgroundJob model constructor.
     * @property {module:model/BackgroundJob}
     */
    BackgroundJob,

    /**
     * The BackgroundJobStep model constructor.
     * @property {module:model/BackgroundJobStep}
     */
    BackgroundJobStep,

    /**
     * The BadRequestException model constructor.
     * @property {module:model/BadRequestException}
     */
    BadRequestException,

    /**
     * The BaseTrackerFieldChoiceOption model constructor.
     * @property {module:model/BaseTrackerFieldChoiceOption}
     */
    BaseTrackerFieldChoiceOption,

    /**
     * The BaseTrackerFieldPermission model constructor.
     * @property {module:model/BaseTrackerFieldPermission}
     */
    BaseTrackerFieldPermission,

    /**
     * The Baseline model constructor.
     * @property {module:model/Baseline}
     */
    Baseline,

    /**
     * The BatchGetTrackerItemReviewsRequest model constructor.
     * @property {module:model/BatchGetTrackerItemReviewsRequest}
     */
    BatchGetTrackerItemReviewsRequest,

    /**
     * The BoolField model constructor.
     * @property {module:model/BoolField}
     */
    BoolField,

    /**
     * The BoolFieldValue model constructor.
     * @property {module:model/BoolFieldValue}
     */
    BoolFieldValue,

    /**
     * The BranchReference model constructor.
     * @property {module:model/BranchReference}
     */
    BranchReference,

    /**
     * The BulkOperationResponse model constructor.
     * @property {module:model/BulkOperationResponse}
     */
    BulkOperationResponse,

    /**
     * The ChoiceDocuments model constructor.
     * @property {module:model/ChoiceDocuments}
     */
    ChoiceDocuments,

    /**
     * The ChoiceFieldMultiValue model constructor.
     * @property {module:model/ChoiceFieldMultiValue}
     */
    ChoiceFieldMultiValue,

    /**
     * The ChoiceFieldValue model constructor.
     * @property {module:model/ChoiceFieldValue}
     */
    ChoiceFieldValue,

    /**
     * The ChoiceMembers model constructor.
     * @property {module:model/ChoiceMembers}
     */
    ChoiceMembers,

    /**
     * The ChoiceOptionReference model constructor.
     * @property {module:model/ChoiceOptionReference}
     */
    ChoiceOptionReference,

    /**
     * The ChoiceOptions model constructor.
     * @property {module:model/ChoiceOptions}
     */
    ChoiceOptions,

    /**
     * The ChoiceOptionsChoiceOption model constructor.
     * @property {module:model/ChoiceOptionsChoiceOption}
     */
    ChoiceOptionsChoiceOption,

    /**
     * The ChoiceProjects model constructor.
     * @property {module:model/ChoiceProjects}
     */
    ChoiceProjects,

    /**
     * The ChoiceRepositories model constructor.
     * @property {module:model/ChoiceRepositories}
     */
    ChoiceRepositories,

    /**
     * The ChoiceTrackers model constructor.
     * @property {module:model/ChoiceTrackers}
     */
    ChoiceTrackers,

    /**
     * The ChoiceUsers model constructor.
     * @property {module:model/ChoiceUsers}
     */
    ChoiceUsers,

    /**
     * The ChoiceWorkConfigItems model constructor.
     * @property {module:model/ChoiceWorkConfigItems}
     */
    ChoiceWorkConfigItems,

    /**
     * The ColorField model constructor.
     * @property {module:model/ColorField}
     */
    ColorField,

    /**
     * The ColorFieldValue model constructor.
     * @property {module:model/ColorFieldValue}
     */
    ColorFieldValue,

    /**
     * The Comment model constructor.
     * @property {module:model/Comment}
     */
    Comment,

    /**
     * The CommentReference model constructor.
     * @property {module:model/CommentReference}
     */
    CommentReference,

    /**
     * The CountryField model constructor.
     * @property {module:model/CountryField}
     */
    CountryField,

    /**
     * The CountryFieldMultiValue model constructor.
     * @property {module:model/CountryFieldMultiValue}
     */
    CountryFieldMultiValue,

    /**
     * The CountryFieldValue model constructor.
     * @property {module:model/CountryFieldValue}
     */
    CountryFieldValue,

    /**
     * The CreateBaselineRequest model constructor.
     * @property {module:model/CreateBaselineRequest}
     */
    CreateBaselineRequest,

    /**
     * The CreateTestRunFromTestSetsRequest model constructor.
     * @property {module:model/CreateTestRunFromTestSetsRequest}
     */
    CreateTestRunFromTestSetsRequest,

    /**
     * The CreateTestRunRequest model constructor.
     * @property {module:model/CreateTestRunRequest}
     */
    CreateTestRunRequest,

    /**
     * The CrossProjectDependency model constructor.
     * @property {module:model/CrossProjectDependency}
     */
    CrossProjectDependency,

    /**
     * The DateField model constructor.
     * @property {module:model/DateField}
     */
    DateField,

    /**
     * The DateFieldValue model constructor.
     * @property {module:model/DateFieldValue}
     */
    DateFieldValue,

    /**
     * The DecimalField model constructor.
     * @property {module:model/DecimalField}
     */
    DecimalField,

    /**
     * The DecimalFieldValue model constructor.
     * @property {module:model/DecimalFieldValue}
     */
    DecimalFieldValue,

    /**
     * The DefaultBackgroundJobStatusInfo model constructor.
     * @property {module:model/DefaultBackgroundJobStatusInfo}
     */
    DefaultBackgroundJobStatusInfo,

    /**
     * The DefaultFieldSingleValue model constructor.
     * @property {module:model/DefaultFieldSingleValue}
     */
    DefaultFieldSingleValue,

    /**
     * The DefaultMultiFieldValue model constructor.
     * @property {module:model/DefaultMultiFieldValue}
     */
    DefaultMultiFieldValue,

    /**
     * The DependencyAttribute model constructor.
     * @property {module:model/DependencyAttribute}
     */
    DependencyAttribute,

    /**
     * The DependencyEntityReference model constructor.
     * @property {module:model/DependencyEntityReference}
     */
    DependencyEntityReference,

    /**
     * The DependencyFinderJobStatusInfo model constructor.
     * @property {module:model/DependencyFinderJobStatusInfo}
     */
    DependencyFinderJobStatusInfo,

    /**
     * The DeployProject model constructor.
     * @property {module:model/DeployProject}
     */
    DeployProject,

    /**
     * The DeploymentModel model constructor.
     * @property {module:model/DeploymentModel}
     */
    DeploymentModel,

    /**
     * The DeploymentProjectExportSettings model constructor.
     * @property {module:model/DeploymentProjectExportSettings}
     */
    DeploymentProjectExportSettings,

    /**
     * The DeploymentTrackerExportSettings model constructor.
     * @property {module:model/DeploymentTrackerExportSettings}
     */
    DeploymentTrackerExportSettings,

    /**
     * The DownstreamTrackerItemReference model constructor.
     * @property {module:model/DownstreamTrackerItemReference}
     */
    DownstreamTrackerItemReference,

    /**
     * The DurationField model constructor.
     * @property {module:model/DurationField}
     */
    DurationField,

    /**
     * The DurationFieldValue model constructor.
     * @property {module:model/DurationFieldValue}
     */
    DurationFieldValue,

    /**
     * The EditComment model constructor.
     * @property {module:model/EditComment}
     */
    EditComment,

    /**
     * The ExportForDeploymentRequest model constructor.
     * @property {module:model/ExportForDeploymentRequest}
     */
    ExportForDeploymentRequest,

    /**
     * The ExportProject model constructor.
     * @property {module:model/ExportProject}
     */
    ExportProject,

    /**
     * The ExportToWordRequest model constructor.
     * @property {module:model/ExportToWordRequest}
     */
    ExportToWordRequest,

    /**
     * The ExternalScmRepositoryRequest model constructor.
     * @property {module:model/ExternalScmRepositoryRequest}
     */
    ExternalScmRepositoryRequest,

    /**
     * The FailedOperation model constructor.
     * @property {module:model/FailedOperation}
     */
    FailedOperation,

    /**
     * The FieldLayoutGroups model constructor.
     * @property {module:model/FieldLayoutGroups}
     */
    FieldLayoutGroups,

    /**
     * The FieldLayoutSettings model constructor.
     * @property {module:model/FieldLayoutSettings}
     */
    FieldLayoutSettings,

    /**
     * The FieldReference model constructor.
     * @property {module:model/FieldReference}
     */
    FieldReference,

    /**
     * The IncomingTrackerItemAssociation model constructor.
     * @property {module:model/IncomingTrackerItemAssociation}
     */
    IncomingTrackerItemAssociation,

    /**
     * The IntegerField model constructor.
     * @property {module:model/IntegerField}
     */
    IntegerField,

    /**
     * The IntegerFieldValue model constructor.
     * @property {module:model/IntegerFieldValue}
     */
    IntegerFieldValue,

    /**
     * The InternalServerErrorException model constructor.
     * @property {module:model/InternalServerErrorException}
     */
    InternalServerErrorException,

    /**
     * The InvalidParametersException model constructor.
     * @property {module:model/InvalidParametersException}
     */
    InvalidParametersException,

    /**
     * The JobReference model constructor.
     * @property {module:model/JobReference}
     */
    JobReference,

    /**
     * The JsonView model constructor.
     * @property {module:model/JsonView}
     */
    JsonView,

    /**
     * The Label model constructor.
     * @property {module:model/Label}
     */
    Label,

    /**
     * The LanguageField model constructor.
     * @property {module:model/LanguageField}
     */
    LanguageField,

    /**
     * The LanguageFieldMultiValue model constructor.
     * @property {module:model/LanguageFieldMultiValue}
     */
    LanguageFieldMultiValue,

    /**
     * The LanguageFieldValue model constructor.
     * @property {module:model/LanguageFieldValue}
     */
    LanguageFieldValue,

    /**
     * The LayoutField model constructor.
     * @property {module:model/LayoutField}
     */
    LayoutField,

    /**
     * The LockInfo model constructor.
     * @property {module:model/LockInfo}
     */
    LockInfo,

    /**
     * The LockRequest model constructor.
     * @property {module:model/LockRequest}
     */
    LockRequest,

    /**
     * The MaintenanceMode model constructor.
     * @property {module:model/MaintenanceMode}
     */
    MaintenanceMode,

    /**
     * The MaintenanceModeProperties model constructor.
     * @property {module:model/MaintenanceModeProperties}
     */
    MaintenanceModeProperties,

    /**
     * The MemberField model constructor.
     * @property {module:model/MemberField}
     */
    MemberField,

    /**
     * The MemberReferenceSearchResult model constructor.
     * @property {module:model/MemberReferenceSearchResult}
     */
    MemberReferenceSearchResult,

    /**
     * The NotImplementedException model constructor.
     * @property {module:model/NotImplementedException}
     */
    NotImplementedException,

    /**
     * The NotSupportedFieldValue model constructor.
     * @property {module:model/NotSupportedFieldValue}
     */
    NotSupportedFieldValue,

    /**
     * The OptionChoiceField model constructor.
     * @property {module:model/OptionChoiceField}
     */
    OptionChoiceField,

    /**
     * The OutgoingTrackerItemAssociation model constructor.
     * @property {module:model/OutgoingTrackerItemAssociation}
     */
    OutgoingTrackerItemAssociation,

    /**
     * The OutlineIndex model constructor.
     * @property {module:model/OutlineIndex}
     */
    OutlineIndex,

    /**
     * The OutlineItem model constructor.
     * @property {module:model/OutlineItem}
     */
    OutlineItem,

    /**
     * The OutlineItemSearchResult model constructor.
     * @property {module:model/OutlineItemSearchResult}
     */
    OutlineItemSearchResult,

    /**
     * The OutlineWiki model constructor.
     * @property {module:model/OutlineWiki}
     */
    OutlineWiki,

    /**
     * The PaginatedAuditPermissionsResponse model constructor.
     * @property {module:model/PaginatedAuditPermissionsResponse}
     */
    PaginatedAuditPermissionsResponse,

    /**
     * The PerStatusFieldPermission model constructor.
     * @property {module:model/PerStatusFieldPermission}
     */
    PerStatusFieldPermission,

    /**
     * The PermissionIdsRequest model constructor.
     * @property {module:model/PermissionIdsRequest}
     */
    PermissionIdsRequest,

    /**
     * The PostComment model constructor.
     * @property {module:model/PostComment}
     */
    PostComment,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The ProjectBaselineReference model constructor.
     * @property {module:model/ProjectBaselineReference}
     */
    ProjectBaselineReference,

    /**
     * The ProjectChoiceField model constructor.
     * @property {module:model/ProjectChoiceField}
     */
    ProjectChoiceField,

    /**
     * The ProjectFilteringRequest model constructor.
     * @property {module:model/ProjectFilteringRequest}
     */
    ProjectFilteringRequest,

    /**
     * The ProjectMemberPermissions model constructor.
     * @property {module:model/ProjectMemberPermissions}
     */
    ProjectMemberPermissions,

    /**
     * The ProjectReference model constructor.
     * @property {module:model/ProjectReference}
     */
    ProjectReference,

    /**
     * The ProjectRoleReference model constructor.
     * @property {module:model/ProjectRoleReference}
     */
    ProjectRoleReference,

    /**
     * The ProjectSearchResult model constructor.
     * @property {module:model/ProjectSearchResult}
     */
    ProjectSearchResult,

    /**
     * The ProjectWithTrackerTypesReference model constructor.
     * @property {module:model/ProjectWithTrackerTypesReference}
     */
    ProjectWithTrackerTypesReference,

    /**
     * The ReferenceField model constructor.
     * @property {module:model/ReferenceField}
     */
    ReferenceField,

    /**
     * The ReferenceFilterBasedChoiceReferenceFilter model constructor.
     * @property {module:model/ReferenceFilterBasedChoiceReferenceFilter}
     */
    ReferenceFilterBasedChoiceReferenceFilter,

    /**
     * The ReferenceSearchResult model constructor.
     * @property {module:model/ReferenceSearchResult}
     */
    ReferenceSearchResult,

    /**
     * The ReferredTestStepFieldValue model constructor.
     * @property {module:model/ReferredTestStepFieldValue}
     */
    ReferredTestStepFieldValue,

    /**
     * The RemoteMigrationFile model constructor.
     * @property {module:model/RemoteMigrationFile}
     */
    RemoteMigrationFile,

    /**
     * The ReportAggregate model constructor.
     * @property {module:model/ReportAggregate}
     */
    ReportAggregate,

    /**
     * The ReportCell model constructor.
     * @property {module:model/ReportCell}
     */
    ReportCell,

    /**
     * The ReportColumn model constructor.
     * @property {module:model/ReportColumn}
     */
    ReportColumn,

    /**
     * The ReportColumnSettings model constructor.
     * @property {module:model/ReportColumnSettings}
     */
    ReportColumnSettings,

    /**
     * The ReportGroup model constructor.
     * @property {module:model/ReportGroup}
     */
    ReportGroup,

    /**
     * The ReportGroupWithGroups model constructor.
     * @property {module:model/ReportGroupWithGroups}
     */
    ReportGroupWithGroups,

    /**
     * The ReportGroupWithReferencedRows model constructor.
     * @property {module:model/ReportGroupWithReferencedRows}
     */
    ReportGroupWithReferencedRows,

    /**
     * The ReportGroupWithRows model constructor.
     * @property {module:model/ReportGroupWithRows}
     */
    ReportGroupWithRows,

    /**
     * The ReportItem model constructor.
     * @property {module:model/ReportItem}
     */
    ReportItem,

    /**
     * The ReportItemReference model constructor.
     * @property {module:model/ReportItemReference}
     */
    ReportItemReference,

    /**
     * The ReportItemResult model constructor.
     * @property {module:model/ReportItemResult}
     */
    ReportItemResult,

    /**
     * The ReportPagingInformation model constructor.
     * @property {module:model/ReportPagingInformation}
     */
    ReportPagingInformation,

    /**
     * The ReportPermission model constructor.
     * @property {module:model/ReportPermission}
     */
    ReportPermission,

    /**
     * The ReportReference model constructor.
     * @property {module:model/ReportReference}
     */
    ReportReference,

    /**
     * The ReportReferenceLevel model constructor.
     * @property {module:model/ReportReferenceLevel}
     */
    ReportReferenceLevel,

    /**
     * The ReportReferenceLevelSettings model constructor.
     * @property {module:model/ReportReferenceLevelSettings}
     */
    ReportReferenceLevelSettings,

    /**
     * The ReportReferencedRow model constructor.
     * @property {module:model/ReportReferencedRow}
     */
    ReportReferencedRow,

    /**
     * The ReportResult model constructor.
     * @property {module:model/ReportResult}
     */
    ReportResult,

    /**
     * The ReportRow model constructor.
     * @property {module:model/ReportRow}
     */
    ReportRow,

    /**
     * The RepositoryChoiceField model constructor.
     * @property {module:model/RepositoryChoiceField}
     */
    RepositoryChoiceField,

    /**
     * The RepositoryReference model constructor.
     * @property {module:model/RepositoryReference}
     */
    RepositoryReference,

    /**
     * The ResizableReportColumnSettings model constructor.
     * @property {module:model/ResizableReportColumnSettings}
     */
    ResizableReportColumnSettings,

    /**
     * The ResourceForbiddenException model constructor.
     * @property {module:model/ResourceForbiddenException}
     */
    ResourceForbiddenException,

    /**
     * The ResourceLockedException model constructor.
     * @property {module:model/ResourceLockedException}
     */
    ResourceLockedException,

    /**
     * The ResourceNotFoundException model constructor.
     * @property {module:model/ResourceNotFoundException}
     */
    ResourceNotFoundException,

    /**
     * The ResourceUnauthorizedException model constructor.
     * @property {module:model/ResourceUnauthorizedException}
     */
    ResourceUnauthorizedException,

    /**
     * The RestException model constructor.
     * @property {module:model/RestException}
     */
    RestException,

    /**
     * The ReviewMemberReferenceField model constructor.
     * @property {module:model/ReviewMemberReferenceField}
     */
    ReviewMemberReferenceField,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The RoleReference model constructor.
     * @property {module:model/RoleReference}
     */
    RoleReference,

    /**
     * The RoleWithPermissions model constructor.
     * @property {module:model/RoleWithPermissions}
     */
    RoleWithPermissions,

    /**
     * The SameAsFieldPermission model constructor.
     * @property {module:model/SameAsFieldPermission}
     */
    SameAsFieldPermission,

    /**
     * The SharedFieldReference model constructor.
     * @property {module:model/SharedFieldReference}
     */
    SharedFieldReference,

    /**
     * The SimpleReportSettings model constructor.
     * @property {module:model/SimpleReportSettings}
     */
    SimpleReportSettings,

    /**
     * The SingleFieldPermission model constructor.
     * @property {module:model/SingleFieldPermission}
     */
    SingleFieldPermission,

    /**
     * The StatusLayout model constructor.
     * @property {module:model/StatusLayout}
     */
    StatusLayout,

    /**
     * The SystemStatus model constructor.
     * @property {module:model/SystemStatus}
     */
    SystemStatus,

    /**
     * The TableField model constructor.
     * @property {module:model/TableField}
     */
    TableField,

    /**
     * The TableFieldValue model constructor.
     * @property {module:model/TableFieldValue}
     */
    TableFieldValue,

    /**
     * The TestRunResult model constructor.
     * @property {module:model/TestRunResult}
     */
    TestRunResult,

    /**
     * The TextField model constructor.
     * @property {module:model/TextField}
     */
    TextField,

    /**
     * The TextFieldValue model constructor.
     * @property {module:model/TextFieldValue}
     */
    TextFieldValue,

    /**
     * The TooManyRequestsException model constructor.
     * @property {module:model/TooManyRequestsException}
     */
    TooManyRequestsException,

    /**
     * The TraceabilityInitialLevelFilter model constructor.
     * @property {module:model/TraceabilityInitialLevelFilter}
     */
    TraceabilityInitialLevelFilter,

    /**
     * The TraceabilityItem model constructor.
     * @property {module:model/TraceabilityItem}
     */
    TraceabilityItem,

    /**
     * The TraceabilityLevelFilter model constructor.
     * @property {module:model/TraceabilityLevelFilter}
     */
    TraceabilityLevelFilter,

    /**
     * The TraceabilityResult model constructor.
     * @property {module:model/TraceabilityResult}
     */
    TraceabilityResult,

    /**
     * The Tracker model constructor.
     * @property {module:model/Tracker}
     */
    Tracker,

    /**
     * The TrackerBaselineReference model constructor.
     * @property {module:model/TrackerBaselineReference}
     */
    TrackerBaselineReference,

    /**
     * The TrackerBasicInformation model constructor.
     * @property {module:model/TrackerBasicInformation}
     */
    TrackerBasicInformation,

    /**
     * The TrackerChoiceField model constructor.
     * @property {module:model/TrackerChoiceField}
     */
    TrackerChoiceField,

    /**
     * The TrackerConfiguration model constructor.
     * @property {module:model/TrackerConfiguration}
     */
    TrackerConfiguration,

    /**
     * The TrackerField model constructor.
     * @property {module:model/TrackerField}
     */
    TrackerField,

    /**
     * The TrackerFieldComputedFieldReference model constructor.
     * @property {module:model/TrackerFieldComputedFieldReference}
     */
    TrackerFieldComputedFieldReference,

    /**
     * The TrackerFieldDateFieldSettings model constructor.
     * @property {module:model/TrackerFieldDateFieldSettings}
     */
    TrackerFieldDateFieldSettings,

    /**
     * The TrackerFieldDependency model constructor.
     * @property {module:model/TrackerFieldDependency}
     */
    TrackerFieldDependency,

    /**
     * The TrackerFieldLayoutSettings model constructor.
     * @property {module:model/TrackerFieldLayoutSettings}
     */
    TrackerFieldLayoutSettings,

    /**
     * The TrackerFieldPermissionAccessPermission model constructor.
     * @property {module:model/TrackerFieldPermissionAccessPermission}
     */
    TrackerFieldPermissionAccessPermission,

    /**
     * The TrackerFieldPermissions model constructor.
     * @property {module:model/TrackerFieldPermissions}
     */
    TrackerFieldPermissions,

    /**
     * The TrackerFieldServiceDeskField model constructor.
     * @property {module:model/TrackerFieldServiceDeskField}
     */
    TrackerFieldServiceDeskField,

    /**
     * The TrackerFieldStatusPermissions model constructor.
     * @property {module:model/TrackerFieldStatusPermissions}
     */
    TrackerFieldStatusPermissions,

    /**
     * The TrackerFieldsStatusPermissions model constructor.
     * @property {module:model/TrackerFieldsStatusPermissions}
     */
    TrackerFieldsStatusPermissions,

    /**
     * The TrackerFilteringRequest model constructor.
     * @property {module:model/TrackerFilteringRequest}
     */
    TrackerFilteringRequest,

    /**
     * The TrackerIdIconBody model constructor.
     * @property {module:model/TrackerIdIconBody}
     */
    TrackerIdIconBody,

    /**
     * The TrackerItem model constructor.
     * @property {module:model/TrackerItem}
     */
    TrackerItem,

    /**
     * The TrackerItemAttachmentRequest model constructor.
     * @property {module:model/TrackerItemAttachmentRequest}
     */
    TrackerItemAttachmentRequest,

    /**
     * The TrackerItemChange model constructor.
     * @property {module:model/TrackerItemChange}
     */
    TrackerItemChange,

    /**
     * The TrackerItemChildReference model constructor.
     * @property {module:model/TrackerItemChildReference}
     */
    TrackerItemChildReference,

    /**
     * The TrackerItemChoiceField model constructor.
     * @property {module:model/TrackerItemChoiceField}
     */
    TrackerItemChoiceField,

    /**
     * The TrackerItemField model constructor.
     * @property {module:model/TrackerItemField}
     */
    TrackerItemField,

    /**
     * The TrackerItemFieldAccessibility model constructor.
     * @property {module:model/TrackerItemFieldAccessibility}
     */
    TrackerItemFieldAccessibility,

    /**
     * The TrackerItemFieldAccessibilityList model constructor.
     * @property {module:model/TrackerItemFieldAccessibilityList}
     */
    TrackerItemFieldAccessibilityList,

    /**
     * The TrackerItemFieldMapping model constructor.
     * @property {module:model/TrackerItemFieldMapping}
     */
    TrackerItemFieldMapping,

    /**
     * The TrackerItemFieldMappingInfo model constructor.
     * @property {module:model/TrackerItemFieldMappingInfo}
     */
    TrackerItemFieldMappingInfo,

    /**
     * The TrackerItemFieldMappingPair model constructor.
     * @property {module:model/TrackerItemFieldMappingPair}
     */
    TrackerItemFieldMappingPair,

    /**
     * The TrackerItemFieldMappingPossiblePair model constructor.
     * @property {module:model/TrackerItemFieldMappingPossiblePair}
     */
    TrackerItemFieldMappingPossiblePair,

    /**
     * The TrackerItemHistory model constructor.
     * @property {module:model/TrackerItemHistory}
     */
    TrackerItemHistory,

    /**
     * The TrackerItemHistoryRevision model constructor.
     * @property {module:model/TrackerItemHistoryRevision}
     */
    TrackerItemHistoryRevision,

    /**
     * The TrackerItemMoveRequest model constructor.
     * @property {module:model/TrackerItemMoveRequest}
     */
    TrackerItemMoveRequest,

    /**
     * The TrackerItemReference model constructor.
     * @property {module:model/TrackerItemReference}
     */
    TrackerItemReference,

    /**
     * The TrackerItemReferenceData model constructor.
     * @property {module:model/TrackerItemReferenceData}
     */
    TrackerItemReferenceData,

    /**
     * The TrackerItemReferenceSearchResult model constructor.
     * @property {module:model/TrackerItemReferenceSearchResult}
     */
    TrackerItemReferenceSearchResult,

    /**
     * The TrackerItemRelationsResult model constructor.
     * @property {module:model/TrackerItemRelationsResult}
     */
    TrackerItemRelationsResult,

    /**
     * The TrackerItemReview model constructor.
     * @property {module:model/TrackerItemReview}
     */
    TrackerItemReview,

    /**
     * The TrackerItemReviewConfig model constructor.
     * @property {module:model/TrackerItemReviewConfig}
     */
    TrackerItemReviewConfig,

    /**
     * The TrackerItemReviewExport model constructor.
     * @property {module:model/TrackerItemReviewExport}
     */
    TrackerItemReviewExport,

    /**
     * The TrackerItemReviewVote model constructor.
     * @property {module:model/TrackerItemReviewVote}
     */
    TrackerItemReviewVote,

    /**
     * The TrackerItemReviewVoteExport model constructor.
     * @property {module:model/TrackerItemReviewVoteExport}
     */
    TrackerItemReviewVoteExport,

    /**
     * The TrackerItemRevision model constructor.
     * @property {module:model/TrackerItemRevision}
     */
    TrackerItemRevision,

    /**
     * The TrackerItemRowChange model constructor.
     * @property {module:model/TrackerItemRowChange}
     */
    TrackerItemRowChange,

    /**
     * The TrackerItemSearchRequest model constructor.
     * @property {module:model/TrackerItemSearchRequest}
     */
    TrackerItemSearchRequest,

    /**
     * The TrackerItemSearchResult model constructor.
     * @property {module:model/TrackerItemSearchResult}
     */
    TrackerItemSearchResult,

    /**
     * The TrackerItemWithTrackerItemReviewsExport model constructor.
     * @property {module:model/TrackerItemWithTrackerItemReviewsExport}
     */
    TrackerItemWithTrackerItemReviewsExport,

    /**
     * The TrackerItemsRequest model constructor.
     * @property {module:model/TrackerItemsRequest}
     */
    TrackerItemsRequest,

    /**
     * The TrackerPermission model constructor.
     * @property {module:model/TrackerPermission}
     */
    TrackerPermission,

    /**
     * The TrackerPermissionReference model constructor.
     * @property {module:model/TrackerPermissionReference}
     */
    TrackerPermissionReference,

    /**
     * The TrackerReference model constructor.
     * @property {module:model/TrackerReference}
     */
    TrackerReference,

    /**
     * The TrackerReportSettings model constructor.
     * @property {module:model/TrackerReportSettings}
     */
    TrackerReportSettings,

    /**
     * The TrackerSearchResult model constructor.
     * @property {module:model/TrackerSearchResult}
     */
    TrackerSearchResult,

    /**
     * The TrackerTree model constructor.
     * @property {module:model/TrackerTree}
     */
    TrackerTree,

    /**
     * The TrackerType model constructor.
     * @property {module:model/TrackerType}
     */
    TrackerType,

    /**
     * The TrackerTypeReference model constructor.
     * @property {module:model/TrackerTypeReference}
     */
    TrackerTypeReference,

    /**
     * The TrackerWorkingSet model constructor.
     * @property {module:model/TrackerWorkingSet}
     */
    TrackerWorkingSet,

    /**
     * The UnrestrictedFieldPermission model constructor.
     * @property {module:model/UnrestrictedFieldPermission}
     */
    UnrestrictedFieldPermission,

    /**
     * The UpdateAttachment model constructor.
     * @property {module:model/UpdateAttachment}
     */
    UpdateAttachment,

    /**
     * The UpdateTestCaseRunRequest model constructor.
     * @property {module:model/UpdateTestCaseRunRequest}
     */
    UpdateTestCaseRunRequest,

    /**
     * The UpdateTestRunRequest model constructor.
     * @property {module:model/UpdateTestRunRequest}
     */
    UpdateTestRunRequest,

    /**
     * The UpdateTrackerItemChildrenRequest model constructor.
     * @property {module:model/UpdateTrackerItemChildrenRequest}
     */
    UpdateTrackerItemChildrenRequest,

    /**
     * The UpdateTrackerItemField model constructor.
     * @property {module:model/UpdateTrackerItemField}
     */
    UpdateTrackerItemField,

    /**
     * The UpdateTrackerItemFieldWithItemId model constructor.
     * @property {module:model/UpdateTrackerItemFieldWithItemId}
     */
    UpdateTrackerItemFieldWithItemId,

    /**
     * The UpdateTrackerItemTableField model constructor.
     * @property {module:model/UpdateTrackerItemTableField}
     */
    UpdateTrackerItemTableField,

    /**
     * The UploadAttachment model constructor.
     * @property {module:model/UploadAttachment}
     */
    UploadAttachment,

    /**
     * The UpstreamTrackerItemReference model constructor.
     * @property {module:model/UpstreamTrackerItemReference}
     */
    UpstreamTrackerItemReference,

    /**
     * The UrlField model constructor.
     * @property {module:model/UrlField}
     */
    UrlField,

    /**
     * The UrlFieldValue model constructor.
     * @property {module:model/UrlFieldValue}
     */
    UrlFieldValue,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserChoiceField model constructor.
     * @property {module:model/UserChoiceField}
     */
    UserChoiceField,

    /**
     * The UserFilteringRequest model constructor.
     * @property {module:model/UserFilteringRequest}
     */
    UserFilteringRequest,

    /**
     * The UserGroup model constructor.
     * @property {module:model/UserGroup}
     */
    UserGroup,

    /**
     * The UserGroupReference model constructor.
     * @property {module:model/UserGroupReference}
     */
    UserGroupReference,

    /**
     * The UserReference model constructor.
     * @property {module:model/UserReference}
     */
    UserReference,

    /**
     * The UserReferenceSearchResult model constructor.
     * @property {module:model/UserReferenceSearchResult}
     */
    UserReferenceSearchResult,

    /**
     * The UserSearchResult model constructor.
     * @property {module:model/UserSearchResult}
     */
    UserSearchResult,

    /**
     * The WikiOutlineSearchResult model constructor.
     * @property {module:model/WikiOutlineSearchResult}
     */
    WikiOutlineSearchResult,

    /**
     * The WikiPage model constructor.
     * @property {module:model/WikiPage}
     */
    WikiPage,

    /**
     * The WikiPageReference model constructor.
     * @property {module:model/WikiPageReference}
     */
    WikiPageReference,

    /**
     * The WikiRenderRequest model constructor.
     * @property {module:model/WikiRenderRequest}
     */
    WikiRenderRequest,

    /**
     * The WikiTextField model constructor.
     * @property {module:model/WikiTextField}
     */
    WikiTextField,

    /**
     * The WikiTextFieldMultiValue model constructor.
     * @property {module:model/WikiTextFieldMultiValue}
     */
    WikiTextFieldMultiValue,

    /**
     * The WikiTextFieldValue model constructor.
     * @property {module:model/WikiTextFieldValue}
     */
    WikiTextFieldValue,

    /**
     * The WorkflowTransition model constructor.
     * @property {module:model/WorkflowTransition}
     */
    WorkflowTransition,

    /**
     * The WorkingSetInformation model constructor.
     * @property {module:model/WorkingSetInformation}
     */
    WorkingSetInformation,

    /**
     * The WorkingSetItemMapping model constructor.
     * @property {module:model/WorkingSetItemMapping}
     */
    WorkingSetItemMapping,

    /**
     * The WorkingSetItemsMappingRequest model constructor.
     * @property {module:model/WorkingSetItemsMappingRequest}
     */
    WorkingSetItemsMappingRequest,

    /**
     * The WorkingSetMinimal model constructor.
     * @property {module:model/WorkingSetMinimal}
     */
    WorkingSetMinimal,

    /**
     * The WorkingSetPermissionRequest model constructor.
     * @property {module:model/WorkingSetPermissionRequest}
     */
    WorkingSetPermissionRequest,

    /**
     * The WorkingSetReference model constructor.
     * @property {module:model/WorkingSetReference}
     */
    WorkingSetReference,

    /**
     * The WorkingSetTracker model constructor.
     * @property {module:model/WorkingSetTracker}
     */
    WorkingSetTracker,

    /**
     * The WorkingSetTrackerUpdateRequest model constructor.
     * @property {module:model/WorkingSetTrackerUpdateRequest}
     */
    WorkingSetTrackerUpdateRequest,

    /**
     * The WorkingSetUpdateRequest model constructor.
     * @property {module:model/WorkingSetUpdateRequest}
     */
    WorkingSetUpdateRequest,

    /**
    * The AssociationApi service constructor.
    * @property {module:api/AssociationApi}
    */
    AssociationApi,

    /**
    * The AttachmentApi service constructor.
    * @property {module:api/AttachmentApi}
    */
    AttachmentApi,

    /**
    * The BackgroundJobApi service constructor.
    * @property {module:api/BackgroundJobApi}
    */
    BackgroundJobApi,

    /**
    * The BaselineApi service constructor.
    * @property {module:api/BaselineApi}
    */
    BaselineApi,

    /**
    * The BranchesApi service constructor.
    * @property {module:api/BranchesApi}
    */
    BranchesApi,

    /**
    * The DeploymentApi service constructor.
    * @property {module:api/DeploymentApi}
    */
    DeploymentApi,

    /**
    * The ExportApi service constructor.
    * @property {module:api/ExportApi}
    */
    ExportApi,

    /**
    * The GroupApi service constructor.
    * @property {module:api/GroupApi}
    */
    GroupApi,

    /**
    * The MigrationApi service constructor.
    * @property {module:api/MigrationApi}
    */
    MigrationApi,

    /**
    * The ProjectApi service constructor.
    * @property {module:api/ProjectApi}
    */
    ProjectApi,

    /**
    * The ReportApi service constructor.
    * @property {module:api/ReportApi}
    */
    ReportApi,

    /**
    * The RepositoryItemApi service constructor.
    * @property {module:api/RepositoryItemApi}
    */
    RepositoryItemApi,

    /**
    * The RoleApi service constructor.
    * @property {module:api/RoleApi}
    */
    RoleApi,

    /**
    * The SystemApi service constructor.
    * @property {module:api/SystemApi}
    */
    SystemApi,

    /**
    * The SystemAdministratorApi service constructor.
    * @property {module:api/SystemAdministratorApi}
    */
    SystemAdministratorApi,

    /**
    * The TestManagementApi service constructor.
    * @property {module:api/TestManagementApi}
    */
    TestManagementApi,

    /**
    * The TestRunApi service constructor.
    * @property {module:api/TestRunApi}
    */
    TestRunApi,

    /**
    * The TraceabilityApi service constructor.
    * @property {module:api/TraceabilityApi}
    */
    TraceabilityApi,

    /**
    * The TrackerApi service constructor.
    * @property {module:api/TrackerApi}
    */
    TrackerApi,

    /**
    * The TrackerItemApi service constructor.
    * @property {module:api/TrackerItemApi}
    */
    TrackerItemApi,

    /**
    * The TrackerItemMoveApi service constructor.
    * @property {module:api/TrackerItemMoveApi}
    */
    TrackerItemMoveApi,

    /**
    * The TrackerItemsAttachmentApi service constructor.
    * @property {module:api/TrackerItemsAttachmentApi}
    */
    TrackerItemsAttachmentApi,

    /**
    * The TrackerItemsCommentApi service constructor.
    * @property {module:api/TrackerItemsCommentApi}
    */
    TrackerItemsCommentApi,

    /**
    * The TrackerPermissionApi service constructor.
    * @property {module:api/TrackerPermissionApi}
    */
    TrackerPermissionApi,

    /**
    * The TrackerReportApi service constructor.
    * @property {module:api/TrackerReportApi}
    */
    TrackerReportApi,

    /**
    * The TrackerTreeApi service constructor.
    * @property {module:api/TrackerTreeApi}
    */
    TrackerTreeApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The WikiApi service constructor.
    * @property {module:api/WikiApi}
    */
    WikiApi,

    /**
    * The WikisCommentApi service constructor.
    * @property {module:api/WikisCommentApi}
    */
    WikisCommentApi,

    /**
    * The WorkingSetApi service constructor.
    * @property {module:api/WorkingSetApi}
    */
    WorkingSetApi,

    /**
    * The WorkingSetPermissionApi service constructor.
    * @property {module:api/WorkingSetPermissionApi}
    */
    WorkingSetPermissionApi
};
