/*
 * Codebeamer swagger API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.61
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CodebeamerSwaggerApi);
  }
}(this, function(expect, CodebeamerSwaggerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CodebeamerSwaggerApi.TrackerItemsAttachmentApi();
  });

  describe('(package)', function() {
    describe('TrackerItemsAttachmentApi', function() {
      describe('deleteTrackerItemAttachment', function() {
        it('should call deleteTrackerItemAttachment successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTrackerItemAttachment call and complete the assertions
          /*
          var opts = {};

          instance.deleteTrackerItemAttachment(itemId, attachmentId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CodebeamerSwaggerApi.Attachment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTrackerItemAttachments', function() {
        it('should call deleteTrackerItemAttachments successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTrackerItemAttachments call
          /*
          var opts = {};

          instance.deleteTrackerItemAttachments(itemId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackerItemAttachment', function() {
        it('should call getTrackerItemAttachment successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackerItemAttachment call and complete the assertions
          /*

          instance.getTrackerItemAttachment(itemId, attachmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CodebeamerSwaggerApi.Attachment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackerItemAttachmentContent', function() {
        it('should call getTrackerItemAttachmentContent successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackerItemAttachmentContent call and complete the assertions
          /*

          instance.getTrackerItemAttachmentContent(itemId, attachmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackerItemAttachmentContents', function() {
        it('should call getTrackerItemAttachmentContents successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackerItemAttachmentContents call and complete the assertions
          /*

          instance.getTrackerItemAttachmentContents(itemId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackerItemAttachments', function() {
        it('should call getTrackerItemAttachments successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackerItemAttachments call and complete the assertions
          /*
          var opts = {};

          instance.getTrackerItemAttachments(itemId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CodebeamerSwaggerApi.AttachmentSearchResult);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackerItemsAttachmentContents', function() {
        it('should call getTrackerItemsAttachmentContents successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackerItemsAttachmentContents call and complete the assertions
          /*

          instance.getTrackerItemsAttachmentContents(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateAttachmentOfTrackerItem', function() {
        it('should call updateAttachmentOfTrackerItem successfully', function(done) {
          // TODO: uncomment, update parameter values for updateAttachmentOfTrackerItem call and complete the assertions
          /*
          var opts = {};

          instance.updateAttachmentOfTrackerItem(itemId, attachmentId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CodebeamerSwaggerApi.Attachment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('uploadTrackerItemAttachment', function() {
        it('should call uploadTrackerItemAttachment successfully', function(done) {
          // TODO: uncomment, update parameter values for uploadTrackerItemAttachment call and complete the assertions
          /*
          var opts = {};

          instance.uploadTrackerItemAttachment(itemId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(CodebeamerSwaggerApi.Attachment);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
